'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {countdown,koreanDate,type Site} from '@jjosami/shared';
import type {LiveSnapshot} from '@/server/providers';
import {External,Icon} from '../ui';
import {NavLink} from '../navigation';
export function Home({site,initialLive}:{site:Site;initialLive:LiveSnapshot}){const {profile:p,anniversaries:dates}=site;const [tab,setTab]=useState('intro'),[today,setToday]=useState(koreanDate),[live,setLive]=useState(initialLive);const keyring=useRef<HTMLDivElement>(null),info=useRef<HTMLDivElement>(null);const selected=dates.find(d=>d.key===tab),fan=p.fields.find(f=>f.id==='fan'&&f.visible&&f.value);
 useEffect(()=>{const refresh=()=>{if(document.hidden)return;setToday(koreanDate());fetch('/api/live',{cache:'no-store'}).then(r=>r.json()).then(r=>{if(r.data)setLive(r.data)}).catch(()=>{})};const timer=setInterval(refresh,60000);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',refresh)}},[]);
 const change=(value:string)=>{setTab(value);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)info.current?.animate([{opacity:.3,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:350,easing:'cubic-bezier(.16,1,.3,1)'})};
 return <><section className="charm-hero"><div className="charm-copy"><h1>{p.name}</h1><p className="charm-intro">{p.short}</p><p className="charm-guide">프로필, 시그풍, 노래책.<br/>{p.name}의 방송을 한곳에서.</p><div className="charm-actions"><External href={p.channel} className="btn primary" soop>방송국 바로가기</External><NavLink href="/profile" className="text-link">프로필 보기 <Icon name="arrow"/></NavLink></div></div><div className="charm-stage" onPointerMove={e=>{if(e.pointerType==='touch'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;keyring.current?.style.setProperty('--charm-angle',(-7+x*15)+'deg');keyring.current?.style.setProperty('--charm-yaw',(x*12)+'deg');keyring.current?.style.setProperty('--charm-angle-x',(-y*8)+'deg');keyring.current?.style.setProperty('--charm-shine',(50+x*45)+'%')}} onPointerLeave={()=>{keyring.current?.style.removeProperty('--charm-angle');keyring.current?.style.removeProperty('--charm-yaw');keyring.current?.style.removeProperty('--charm-angle-x')}}><div className="charm-object" ref={keyring}><img className="charm-material" src="/assets/acrylic-keyring.png" width="1024" height="1536" alt="" fetchPriority="high"/><div className="charm-print"><img src={p.image} width="210" height="210" alt={p.alt}/></div><a className="charm-name-tag" href={p.channel} target="_blank" rel="noopener noreferrer"><strong>{p.name}</strong><span>SOOP · {p.channel.split('/').filter(Boolean).at(-1)}</span></a></div></div></section><section className="charm-info-strip" aria-label="프로필 정보"><div className="object-tabs" style={{'--selected-label':['intro','birthday','debut'].indexOf(tab)} as CSSProperties}><span className="label-film" aria-hidden="true"/>{[['intro','소개'],['birthday','생일'],['debut','첫 방송']].map(([key,name])=><button key={key} type="button" aria-pressed={tab===key} onClick={()=>change(key)}>{name}</button>)}</div><div id="studio-preview" ref={info} aria-live="polite">{tab==='intro'?<div className="studio-preview-copy"><strong>{p.name}</strong><p>{fan?fan.label+' · '+fan.value:p.short}</p></div>:selected?<div className="studio-preview-copy"><strong>{selected.name}</strong><p>{selected.date.replaceAll('-','.')} <span className="preview-count">{countdown(selected,today)}</span></p></div>:<p>등록된 기념일이 없습니다.</p>}</div><Icon name="soop" className="label-symbol"/></section>
 <section className="home-broadcast" aria-label="방송 상태"><span className={'status '+(live.status==='live'?'success':live.status==='unknown'?'warning':'')}>{live.status==='live'?'방송 중':live.status==='offline'?'방송 종료':'확인 지연'}</span><div className="broadcast-content"><strong>{live.status==='live'?live.title:live.status==='offline'?'SOOP 방송국':'방송 상태를 확인하지 못했습니다'}</strong>{live.lastSuccessAt&&<p>{new Date(live.lastSuccessAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} 확인</p>}</div><External href={live.broadcastUrl||p.channel} className="btn small quiet">방송국 바로가기</External></section>
 <section className="home-dates" aria-label="기념일">{dates.filter(a=>a.visible&&a.type!=='schedule').slice(0,2).map(a=><NavLink href="/calendar" className="date-block" key={a.id}><div><p>{a.type==='debut'?'첫 방송부터 함께한 날':a.name+'까지 남은 날'}</p><strong>{a.date.replaceAll('-','.')}</strong></div><Counter value={countdown(a,today)}/></NavLink>)}</section>
 <section className="milk-menu" aria-label="메뉴 바로가기"><div className="menu-feature"><h2>노래책</h2><p>곡 제목, 가수와 체감 난이도로<br/>등록된 노래를 찾아보세요.</p><NavLink href="/songbook" className="btn small">노래책 열기 <Icon name="arrow"/></NavLink><Icon name="music"/></div><div className="milk-menu-links">{[['profile','user','프로필','프로필 소개'],['signatures','gift','시그풍','이름과 별풍선 개수로 찾기'],['requests','camera','방셀 신청','관리자에게 비공개 신청']].map(([route,icon,name,desc])=><NavLink key={route} href={'/'+route}><Icon name={icon}/><div><h3>{name}</h3><p>{desc}</p></div><Icon name="arrow"/></NavLink>)}</div></section></>}
function Counter({value}:{value:string}){const ref=useRef<HTMLSpanElement>(null);useEffect(()=>{const element=ref.current;if(!element||!/^D[+-]\d+$/.test(value)||matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0;const observer=new IntersectionObserver(entries=>{if(!entries.some(e=>e.isIntersecting))return;const target=Number(value.slice(2)),start=performance.now();const tick=(time:number)=>{const t=Math.min(1,(time-start)/850);element.textContent=value.slice(0,2)+Math.round(target*(1-(1-t)**4));if(t<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);observer.disconnect()},{threshold:.5});observer.observe(element);return()=>{observer.disconnect();cancelAnimationFrame(frame);element.textContent=value}},[value]);return <span className="date-value" ref={ref}>{value}</span>}
