'use client';
import {useEffect,useState} from 'react';
import type {Account,LedgerEntry} from '@jjosami/shared';
import {Pagination,Search,api} from '../client-tools';
import {Empty,ErrorNote,Icon} from '../ui';
const kinds:Record<string,string>={acquire:'획득',roulette:'룰렛 획득',adjust:'조정',fulfill:'이행',invalidate:'무효 처리',reverse:'되돌림',request_complete:'신청 완료',request_reopen:'완료 취소'};
export function Obligations({initial,types}:{initial:{rows:Account[];total:number;page:number;size:number};types:{id:string;name:string}[]}){const [data,setData]=useState(initial),[q,setQ]=useState(''),[type,setType]=useState(''),[remaining,setRemaining]=useState(false),[page,setPage]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false),[expanded,setExpanded]=useState<string|null>(null),[history,setHistory]=useState<LedgerEntry[]>([]),[historyPage,setHistoryPage]=useState(1),[historyMore,setHistoryMore]=useState(false);
 useEffect(()=>{const control=new AbortController(),timer=setTimeout(()=>{setBusy(true);setError('');api<typeof initial>('/api/obligations?'+new URLSearchParams({q,type,remaining:String(remaining),page:String(page)}),{signal:control.signal}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!control.signal.aborted)setBusy(false)});},220);return()=>{clearTimeout(timer);control.abort()}},[q,type,remaining,page]);
 async function open(id:string,more=false){setError('');const next=more?historyPage+1:1;if(!more&&expanded===id){setExpanded(null);return}try{const rows=await api<LedgerEntry[]>('/api/obligations/'+id+'/history?page='+next);setExpanded(id);setHistory(old=>more?[...old,...rows]:rows);setHistoryPage(next);setHistoryMore(rows.length===50)}catch(e){setError((e as Error).message)}}
 return <><div className="obligation-tools"><Search label="닉네임·SOOP 아이디 검색" value={q} onChange={v=>{setQ(v);setPage(1)}}/><label className="checkbox"><input type="checkbox" checked={remaining} onChange={e=>{setRemaining(e.target.checked);setPage(1)}}/>잔여 있는 항목만</label></div><div className="filter-chips"><button className="chip" aria-pressed={!type} onClick={()=>{setType('');setPage(1)}}>전체</button>{types.map(t=><button className="chip" key={t.id} aria-pressed={t.id===type} onClick={()=>{setType(t.id);setPage(1)}}>{t.name}</button>)}</div><ErrorNote message={error}/><section className="public-ledger" aria-label="공개 업보 시트" aria-busy={busy}><div className="ledger-heading"><h2>업보 시트</h2><span>{busy?'검색 중…':`${data.total}개 항목`}</span></div><div className="ledger-columns" aria-hidden="true"><span>시청자·업보</span><span>획득</span><span>조정</span><span>이행</span><span>잔여</span><span/></div>{data.rows.map(a=><div className="ledger-record" key={a.id}><div className="public-ledger-row"><div className="ledger-person"><strong>{a.nickname}</strong><span>{a.soop}</span><small>{a.item} · {a.unit}</small></div><div className="ledger-amounts">{[['획득',a.acquired],['조정',a.adjusted],['이행',a.fulfilled],['잔여',a.balance]].map(([label,n])=><div className={label==='잔여'?'ledger-balance':''} key={label}><small>{label}</small><strong>{Number(n).toLocaleString('ko-KR',{maximumFractionDigits:3})}</strong></div>)}</div><button className="ledger-history-toggle" onClick={()=>void open(a.id)} aria-expanded={expanded===a.id} aria-controls={'history-'+a.id}>변동 내역<Icon name="chevron"/></button></div>{expanded===a.id&&<div id={'history-'+a.id} className="ledger-history"><ol>{history.map(l=><li key={l.id}><span>{kinds[l.kind]||l.kind}{l.reversed?' · 되돌림 완료':''}</span><time>{new Date(l.time).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</time><strong>{l.delta>0?'+':''}{l.delta} {a.unit}</strong></li>)}</ol>{historyMore&&<button className="text-link" onClick={()=>void open(a.id,true)}>이전 내역 더 보기</button>}</div>}</div>)}{!data.rows.length&&<Empty>표시할 업보가 없습니다.</Empty>}</section><Pagination {...data} onChange={setPage}/></>}
