'use client';
import Script from 'next/script';
import {useEffect,useRef,useState} from 'react';
import {ErrorNote,Icon} from '../ui';
import {Field,TextArea,api,useBusy} from '../client-tools';
import {NavLink} from '../navigation';
declare global{interface Window{turnstile?:{render:(el:HTMLElement,options:Record<string,unknown>)=>string;remove:(id:string)=>void;reset:(id:string)=>void}}}
export function RequestForm({siteKey,nonce}:{siteKey:string;nonce?:string}){const [ready,setReady]=useState(false),[token,setToken]=useState(''),[expired,setExpired]=useState(false),[receipt,setReceipt]=useState<{receipt:string;createdAt:string}|null>(null),host=useRef<HTMLDivElement>(null),widget=useRef<string|null>(null),key=useRef({payload:'',id:''}),formRef=useRef<HTMLFormElement>(null),{busy,error,run}=useBusy();
 useEffect(()=>{if(!ready||!host.current||!siteKey||!window.turnstile)return;widget.current=window.turnstile.render(host.current,{sitekey:siteKey,action:'photo-request',theme:document.documentElement.dataset.theme==='dark'?'dark':'light',callback:(value:string)=>{setToken(value);setExpired(false)},'expired-callback':()=>{setToken('');setExpired(true)},'error-callback':()=>{setToken('');setExpired(true)}});return()=>{if(widget.current)window.turnstile?.remove(widget.current)}},[ready,siteKey]);
 if(receipt)return <section className="receipt"><span className="receipt-seal"><Icon name="check"/></span><h1>신청이 접수되었습니다</h1><p>신청 내용은 관리자에게 전달되었습니다.</p><dl><dt>접수번호</dt><dd>{receipt.receipt}</dd><dt>접수시각</dt><dd>{new Date(receipt.createdAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</dd></dl><NavLink href="/" className="btn primary">홈으로 이동</NavLink></section>;
 return <div className="form-layout"><section className="form-intro"><h1>방셀 신청</h1><p>SOOP 닉네임과 아이디를 입력해 주세요.<br/>신청 내용은 관리자만 확인합니다.</p><ul className="process-list"><li><Icon name="mail"/>신청 정보 입력</li><li><Icon name="user"/>관리자가 신청자와 업보 확인</li><li><Icon name="check"/>확인 후 방셀 처리</li></ul></section><form ref={formRef} className="form-panel stack" onSubmit={e=>{e.preventDefault();void run(async()=>{const fd=new FormData(e.currentTarget),data={nickname:String(fd.get('nickname')).trim(),soop:String(fd.get('soop')).trim(),message:String(fd.get('message')).trim()},payload=JSON.stringify(data);if(key.current.payload!==payload)key.current={payload,id:crypto.randomUUID()};try{const saved=await api<{receipt:string;createdAt:string}>('/api/requests',{method:'POST',headers:{'Idempotency-Key':key.current.id},body:JSON.stringify({...data,token})});setReceipt(saved);window.scrollTo({top:0,behavior:'smooth'})}catch(error){if(widget.current)window.turnstile?.reset(widget.current);setToken('');throw error}})}}><Field label="SOOP 닉네임" name="nickname" autoComplete="off" required maxLength={100}/><Field label="SOOP 아이디" name="soop" autoComplete="off" required maxLength={100}/><TextArea label="추가하고 싶은 말 · 선택" name="message" maxLength={1000} rows={5}/>{siteKey?<><Script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit" nonce={nonce} onReady={()=>setReady(true)} onError={()=>setExpired(true)}/><div ref={host} className="turnstile-container"/>{expired&&<p role="status">보안 확인을 다시 진행해 주세요.</p>}</>:<p role="status">현재 신청 접수를 준비 중입니다.</p>}<ErrorNote message={error}/><button type="submit" className="btn primary" disabled={busy||!token}>{busy?'접수 중…':'신청하기'}<Icon name="arrow"/></button></form></div>}
