'use client';
import {useEffect,useId,useRef,useState,type ReactNode,type InputHTMLAttributes,type SelectHTMLAttributes} from 'react';
import {Icon} from './ui';
export class ApiError extends Error{constructor(message:string,public code:string,public status:number){super(message)}}
export async function api<T=any>(url:string,options:RequestInit={}){const r=await fetch(url,{...options,cache:'no-store',headers:{...(options.body&&!(options.body instanceof FormData)?{'Content-Type':'application/json'}:{}),...options.headers}});const json=await r.json().catch(()=>({error:{message:'요청을 처리하지 못했습니다.',code:'NETWORK_ERROR'}}));if(!r.ok)throw new ApiError(json.error?.message||'요청에 실패했습니다.',json.error?.code||'ERROR',r.status);return json.data as T}
const pending=new Map<string,string>();
export async function mutate<T=any>(url:string,data:unknown,method='POST'){const body=JSON.stringify(data),scope=method+url+body,key=pending.get(scope)||crypto.randomUUID();pending.set(scope,key);try{const value=await api<T>(url,{method,body,headers:{'Idempotency-Key':key}});pending.delete(scope);window.dispatchEvent(new Event('site:saved'));return value}catch(e){if(e instanceof ApiError&&e.status<500&&e.status!==429)pending.delete(scope);throw e}}
export function useLoad<T>(url:string,initial?:T){const [data,setData]=useState<T|undefined>(initial),[error,setError]=useState(''),[loading,setLoading]=useState(!initial),[revision,setRevision]=useState(0);const first=useRef(!!initial);useEffect(()=>{if(first.current){first.current=false;return}const controller=new AbortController();setLoading(true);setError('');api<T>(url,{signal:controller.signal}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[url,revision]);return {data,error,loading,reload:()=>setRevision(n=>n+1),setData}}
export function Field({label,...props}:{label:string}&InputHTMLAttributes<HTMLInputElement>){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><input id={id} {...props}/></div>}
export function TextArea({label,...props}:{label:string}&React.TextareaHTMLAttributes<HTMLTextAreaElement>){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><textarea id={id} {...props}/></div>}
export function Select({label,children,...props}:{label:string;children:ReactNode}&SelectHTMLAttributes<HTMLSelectElement>){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><select id={id} {...props}>{children}</select></div>}
export function Check({label,...props}:{label:string}&InputHTMLAttributes<HTMLInputElement>){return <label className="checkbox"><input type="checkbox" {...props}/><span>{label}</span></label>}
export function Dialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null),id=useId();useEffect(()=>{const previous=document.activeElement as HTMLElement;ref.current?.showModal();return()=>{ref.current?.close();previous?.focus()}},[]);return <dialog ref={ref} aria-labelledby={id} onCancel={onClose} onClick={e=>{if(e.target===ref.current){const r=ref.current.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose()}}}><div className="dialog-head"><h2 id={id}>{title}</h2><button type="button" className="icon-btn" onClick={onClose} aria-label="대화상자 닫기"><Icon name="close"/></button></div><div className="dialog-body">{children}</div></dialog>}
export function Pagination({page,size,total,onChange}:{page:number;size:number;total:number;onChange:(page:number)=>void}){const last=Math.max(1,Math.ceil(total/size));return <nav className="pagination" aria-label="페이지 이동"><button className="btn small" disabled={page<=1} onClick={()=>onChange(page-1)}>이전</button><span>{page} / {last}</span><button className="btn small" disabled={page>=last} onClick={()=>onChange(page+1)}>다음</button></nav>}
export function Search({value,onChange,label='검색'}:{value:string;onChange:(v:string)=>void;label?:string}){return <label className="search"><Icon name="search"/><input type="search" value={value} onChange={e=>onChange(e.target.value)} aria-label={label} placeholder={label}/></label>}
export function useBusy(){const [busy,setBusy]=useState(false),[error,setError]=useState('');return {busy,error,setError,run:async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await action()}catch(e){setError(e instanceof Error?e.message:'요청에 실패했습니다.')}finally{setBusy(false)}}}}
export function listParams(input:Record<string,string|string[]|undefined>){const s=new URLSearchParams();Object.entries(input).forEach(([k,v])=>{if(Array.isArray(v))v.forEach(x=>s.append(k,x));else if(v)s.set(k,v)});return s}
