'use client';
import {createContext,useContext,useEffect,useRef,useState,type MouseEvent,type ReactNode} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import Link from 'next/link';
import {Icon} from './ui';
const Navigation=createContext<(href:string)=>void>(()=>{});
const ContentReady=createContext<(path:string)=>void>(()=>{});
export function PageReady({path}:{path?:string}){const pathname=usePathname(),ready=useContext(ContentReady);useEffect(()=>ready(path||pathname),[path,pathname,ready]);return null}
export function MotionProvider({children,header,footer}:{children:ReactNode;header:ReactNode;footer:ReactNode}){const router=useRouter(),pathname=usePathname(),ref=useRef<HTMLElement>(null),busy=useRef(false),next=useRef<string|null>(null),previous=useRef(pathname);
 const [readyPath,setReadyPath]=useState(pathname);
 const go=async(href:string)=>{if(!busy.current&&href.split('?')[0]===pathname){router.push(href);return}next.current=href;if(busy.current)return;busy.current=true;setReadyPath('');const main=ref.current;if(main&&!matchMedia('(prefers-reduced-motion: reduce)').matches)await main.animate([{opacity:1,transform:'none',filter:'blur(0px)'},{opacity:0,transform:'translateY(-12px) rotate(-.6deg)',filter:'blur(2px)'}],{duration:210,easing:'cubic-bezier(.4,0,1,1)',fill:'forwards'}).finished.catch(()=>{});const target=next.current!;next.current=null;if(target.split('?')[0]===pathname){main?.getAnimations().forEach(a=>a.cancel());busy.current=false;setReadyPath(pathname)}router.push(target);};
 useEffect(()=>{if(previous.current===pathname||readyPath!==pathname)return;previous.current=pathname;const main=ref.current;main?.getAnimations().forEach(a=>a.cancel());window.scrollTo({top:0,behavior:'instant'});const finish=()=>{busy.current=false;main?.focus({preventScroll:true});const pending=next.current;next.current=null;if(pending&&pending.split('?')[0]!==pathname)void go(pending)};if(main&&!matchMedia('(prefers-reduced-motion: reduce)').matches)main.animate([{opacity:0,transform:'translateY(20px) rotate(.8deg)',filter:'blur(3px)',clipPath:'inset(0 0 6%)'},{opacity:1,transform:'none',filter:'blur(0px)',clipPath:'inset(0)'}],{duration:460,easing:'cubic-bezier(.16,1,.3,1)'}).finished.then(finish,finish);else finish()},[pathname,readyPath]);
 return <Navigation.Provider value={href=>void go(href)}><ContentReady.Provider value={setReadyPath}>{header}<main id="main-content" ref={ref} tabIndex={-1} className="page" data-route={pathname.slice(1)||'home'} aria-busy={readyPath!==pathname}>{children}</main>{footer}</ContentReady.Provider></Navigation.Provider>
}
export function NavLink({href,children,className='',...rest}:{href:string;children:ReactNode;className?:string;'aria-label'?:string;'aria-current'?:'page'}){const navigate=useContext(Navigation);return <Link href={href} className={className} {...rest} onClick={(e:MouseEvent<HTMLAnchorElement>)=>{if(e.button||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();navigate(href)}}>{children}</Link>}
const nav=[['/','홈'],['/profile','프로필'],['/calendar','캘린더'],['/signatures','시그풍'],['/songbook','노래책'],['/obligations','업보'],['/requests','방셀 신청']];
export function Header({name,logo}:{name:string;logo?:string}){const path=usePathname(),[failedLogo,setFailedLogo]=useState<string|null>(null);return <header className="site-header"><NavLink href="/" className="brand" aria-label={name+' 홈'}>{logo&&failedLogo!==logo?<img className="brand-logo" src={logo} alt={name+' 로고'} onError={()=>setFailedLogo(logo)}/>:<><Icon name="flower" className="brand-mark"/>{name}</>}</NavLink><nav className="nav" aria-label="주 메뉴">{nav.map(([url,label])=><NavLink key={url} href={url} aria-current={path===url?'page':undefined}>{label}</NavLink>)}</nav><ThemeToggle/></header>}
export function ThemeToggle(){const [dark,setDark]=useState(false);useEffect(()=>setDark(document.documentElement.dataset.theme==='dark'),[]);return <button className="theme-toggle" aria-label={(dark?'라이트':'다크')+' 모드로 전환'} aria-pressed={dark} onClick={()=>{const value=dark?'light':'dark';document.documentElement.dataset.theme=value;try{localStorage.setItem('jjosami-theme',value)}catch{}setDark(!dark)}}><Icon name={dark?'moon':'sun'}/><span>{dark?'다크':'라이트'}</span></button>}
export function ApiError({error,reset}:{error:Error;reset:()=>void}){return <div className="route-error"><PageReady/><h1>화면을 불러오지 못했습니다</h1><p>잠시 후 다시 시도해 주세요.</p><button className="btn primary" onClick={reset}>다시 시도</button></div>}
