import 'server-only';
import {createClient,type SupabaseClient} from '@supabase/supabase-js';
import {createServerClient} from '@supabase/ssr';
import {cookies} from 'next/headers';
export class AppError extends Error{constructor(public code:string,message:string,public status=400){super(message)}}
export function env(name:string){if(process.env.VERCEL_ENV==='preview'&&process.env.PREVIEW_DATABASE_ISOLATED!=='true')throw new AppError('PREVIEW_DISABLED','미리보기 환경의 별도 저장소를 설정해 주세요.',503);const value=process.env[name];if(!value)throw new AppError('SERVICE_UNAVAILABLE','현재 서비스를 이용할 수 없습니다. 잠시 후 다시 시도해 주세요.',503);return value}
export const configured=()=>!!(process.env.SUPABASE_URL&&process.env.SUPABASE_PUBLISHABLE_KEY);
export function publicDb(){return createClient(env('SUPABASE_URL'),env('SUPABASE_PUBLISHABLE_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
export function serviceDb(){return createClient(env('SUPABASE_URL'),env('SUPABASE_SECRET_KEY'),{auth:{persistSession:false,autoRefreshToken:false}})}
export async function sessionDb(writable=false){const store=await cookies();return createServerClient(env('SUPABASE_URL'),env('SUPABASE_PUBLISHABLE_KEY'),{cookieOptions:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/'},cookies:{getAll:()=>store.getAll(),setAll:values=>{if(writable)values.forEach(({name,value,options})=>store.set(name,value,{...options,httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/'}))}}})}
export async function requireAdmin(writable=true){const db=await sessionDb(writable);const {data:{user},error}=await db.auth.getUser();if(error||!user)throw new AppError('UNAUTHENTICATED','로그인이 필요합니다.',401);const {data}=await db.from('admin_users').select('active').eq('id',user.id).maybeSingle();if(!data?.active)throw new AppError('FORBIDDEN','관리자 권한이 없습니다.',403);return {db,user}}
export function dbError(error:{code?:string;message?:string}|null){if(!error)return;const m=error.message||'';const messages:Record<string,string>={ACCOUNT_NOT_FOUND:'삭제되었거나 찾을 수 없는 업보입니다. 목록을 다시 불러와 주세요.',VERSION_CONFLICT:'다른 변경이 먼저 저장되었습니다. 최신 내용을 다시 불러와 주세요.',IDEMPOTENCY_CONFLICT:'같은 요청 번호에 다른 내용이 전달되었습니다. 새로 시도해 주세요.',DUPLICATE_SONG:'같은 제목·가수·버전의 곡이 있습니다. 중복 등록을 확인해 주세요.',NEGATIVE_BALANCE:'잔여 수량이 부족합니다.',INVALID_QUANTITY:'수량과 단위를 확인해 주세요.',CATEGORY_IN_USE:'사용 중인 분류입니다. 곡의 분류를 옮기거나 해제해 주세요.',TYPE_UNIT_IN_USE:'기록이 있는 업보 항목의 단위는 변경할 수 없습니다.',ALREADY_REVERSED:'이미 되돌린 기록입니다.',INVALID_TRANSITION:'현재 상태에서 변경할 수 없는 단계입니다.',REVIEW_ALREADY_RESOLVED:'이미 처리한 결과입니다.',CONFIRM_REQUIRED:'변경 내용을 확인해 주세요.',ACCOUNT_VERIFICATION_REQUIRED:'신청자와 업보 사용자를 확인해 주세요.'};const key=Object.keys(messages).find(k=>m.includes(k));if(key)throw new AppError(key,messages[key],['VERSION_CONFLICT','IDEMPOTENCY_CONFLICT','DUPLICATE_SONG','ALREADY_REVERSED','REVIEW_ALREADY_RESOLVED'].includes(key)?409:400);if(error.code==='42501')throw new AppError('FORBIDDEN','접근 권한이 없습니다.',403);throw new AppError('STORAGE_UNAVAILABLE','저장소 요청을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.',503)}
export async function rpc<T>(db:SupabaseClient,name:string,args:Record<string,unknown>={}){const {data,error}=await db.rpc(name,args);dbError(error);return data as T}
