import 'server-only';
import {NextResponse} from 'next/server';
import {z} from '@jjosami/shared';
import {AppError,env,rpc,serviceDb} from './db';
import {createHmac} from 'node:crypto';
export function success(data:unknown,meta?:unknown){return NextResponse.json({data,...(meta?{meta}:{})},{headers:{'Cache-Control':'no-store'}})}
export function failure(error:unknown){if(error instanceof z.ZodError)return NextResponse.json({error:{code:'INVALID_INPUT',message:error.issues[0]?.message||'입력 내용을 확인해 주세요.',fieldErrors:z.flattenError(error).fieldErrors}},{status:400,headers:{'Cache-Control':'no-store'}});const e=error instanceof AppError?error:new AppError('UNAVAILABLE','요청을 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.',503);return NextResponse.json({error:{code:e.code,message:e.message}},{status:e.status,headers:{'Cache-Control':'no-store'}})}
export function sameOrigin(request:Request){const origin=request.headers.get('origin'),expected=new URL(env('SITE_ORIGIN')).origin;if(origin!==expected)throw new AppError('ORIGIN_REJECTED','요청 출처를 확인할 수 없습니다.',403);const site=request.headers.get('sec-fetch-site');if(site&&site!=='same-origin'&&site!=='none')throw new AppError('ORIGIN_REJECTED','다른 사이트에서 보낸 요청입니다.',403)}
export async function rawBody(req:Request,max=262144){if(Number(req.headers.get('content-length'))>max)throw new AppError('TOO_LARGE','요청 내용이 너무 큽니다.',413);const reader=req.body?.getReader();if(!reader)return '';const chunks:Uint8Array[]=[];let size=0;try{while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>max)throw new AppError('TOO_LARGE','요청 내용이 너무 큽니다.',413);chunks.push(r.value)}}finally{await reader.cancel().catch(()=>{})}return Buffer.concat(chunks).toString('utf8')}
export async function jsonBody(req:Request){if(!req.headers.get('content-type')?.includes('application/json'))throw new AppError('INVALID_INPUT','JSON 형식으로 요청해 주세요.',415);try{return JSON.parse(await rawBody(req))}catch(e){if(e instanceof AppError)throw e;throw new AppError('INVALID_INPUT','요청 형식을 확인해 주세요.')}}
export function operationKey(req:Request){const key=req.headers.get('idempotency-key');if(!key||!z.string().uuid().safeParse(key).success)throw new AppError('INVALID_INPUT','요청 번호가 없습니다. 다시 시도해 주세요.');return key}
export async function rateLimit(req:Request,scope:string,limit=20,seconds=60,actor?:string){const trustedIp=process.env.VERCEL==='1'?(req.headers.get('x-vercel-forwarded-for')||'unavailable'):'local';const key=createHmac('sha256',env('RATE_LIMIT_HASH_SECRET')).update(scope+':'+(actor||trustedIp)).digest('hex');if(!await rpc<boolean>(serviceDb(),'consume_limit',{p_key:key,p_limit:limit,p_seconds:seconds}))throw new AppError('RATE_LIMITED','요청이 많습니다. 잠시 후 다시 시도해 주세요.',429)}
export const boundedPage=(s:URLSearchParams)=>({page:Math.max(1,Math.min(100000,Math.floor(Number(s.get('page')))||1)),size:Math.max(1,Math.min(100,Math.floor(Number(s.get('pageSize')))||20))});
