import 'server-only';
import {createHash} from 'node:crypto';
import {youtube,uuid} from '@jjosami/shared';
import {AppError,dbError,env,rpc,serviceDb} from './db';
export async function fetchJson(url:string,hosts:string[],init:RequestInit={},max=524288,timeout=8000,redirects=0):Promise<any>{
 const u=new URL(url);if(u.protocol!=='https:'||!(hosts.includes(u.hostname)||(hosts.includes('archive.org')&&/^(?:ia|dn)[0-9]+\.(?:[a-z]{2}\.)?archive\.org$/.test(u.hostname)))||u.username||u.password||u.port)throw new AppError('PROVIDER_UNAVAILABLE','외부 응답 주소를 확인할 수 없습니다.',503);
 const r=await fetch(url,{...init,redirect:'manual',signal:AbortSignal.timeout(timeout)});if(r.status>=300&&r.status<400){if(hosts.includes('www.youtube.com')||redirects>=3||!r.headers.get('location'))throw new AppError('PROVIDER_UNAVAILABLE','외부 조회를 완료하지 못했습니다.',503);return fetchJson(new URL(r.headers.get('location')!,url).href,hosts,init,max,timeout,redirects+1)}
 if(r.status===404)return null;if(r.status===429||r.status===503)throw new AppError('PROVIDER_RATE_LIMITED','조회가 잠시 제한되었습니다. 잠시 후 다시 시도해 주세요.',429);if(!r.ok||!r.headers.get('content-type')?.includes('json'))throw new AppError('PROVIDER_UNAVAILABLE','외부 조회를 완료하지 못했습니다.',503);
 const reader=r.body!.getReader();let size=0;const chunks:Uint8Array[]=[];try{while(true){const c=await reader.read();if(c.done)break;size+=c.value.length;if(size>max)throw new AppError('PROVIDER_UNAVAILABLE','외부 응답이 허용 크기를 초과했습니다.',503);chunks.push(c.value)}}finally{await reader.cancel().catch(()=>{})}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw new AppError('PROVIDER_UNAVAILABLE','외부 응답을 해석하지 못했습니다.',503)}
}
function lookupsEnabled(){if(process.env.SONGBOOK_LOOKUPS_ENABLED!=='true')throw new AppError('PROVIDER_DISABLED','곡 정보 조회가 비활성화되어 있습니다. 직접 입력으로 등록할 수 있습니다.',503)}
async function cached(provider:string,key:string,load:()=>Promise<any>,ttl=86400){lookupsEnabled();const db=serviceDb(),now=new Date().toISOString(),hash=createHash('sha256').update('adapter-v1|'+key).digest('hex');const {data:old}=await db.from('songbook_lookup_cache').select('*').eq('provider',provider).eq('request_key',hash).gt('expires_at',now).maybeSingle();if(old)return {lookupId:old.id,...old.data};const data=await load();const {data:saved,error}=await db.from('songbook_lookup_cache').upsert({provider,request_key:hash,data,expires_at:new Date(Date.now()+((Array.isArray(data.candidates)&&data.candidates.length===0)||data.preview===null?600:ttl)*1000).toISOString()},{onConflict:'provider,request_key'}).select('id').single();dbError(error);await rpc(db,'prune_lookup_cache');return {lookupId:saved!.id,...data}}
async function mb(path:string){if(!await rpc<boolean>(serviceDb(),'claim_provider',{p_key:'musicbrainz',p_milliseconds:1100}))throw new AppError('PROVIDER_RATE_LIMITED','곡 정보 조회 중입니다. 잠시 후 다시 시도해 주세요.',429);return fetchJson('https://musicbrainz.org/ws/2/'+path,['musicbrainz.org'],{headers:{'User-Agent':process.env.MUSICBRAINZ_USER_AGENT||`Jjosami/1.0 (${env('SITE_ORIGIN')})`,Accept:'application/json'}})}
const plain=(v:unknown,max=200)=>typeof v==='string'?v.slice(0,max):'';
const mbTerm=(s:string)=>'"'+s.replace(/["\\+\-!():^\[\]{}~*?&|/]/g,' ').trim()+'"';
export async function musicSearch(title:string,artist:string,offset=0){return cached('music',[title,artist,offset].join('|'),async()=>{const q='recording:'+mbTerm(title)+(artist?' AND artist:'+mbTerm(artist):'');const data=await mb('recording?'+new URLSearchParams({query:q,fmt:'json',limit:'20',offset:String(offset)}));return {total:data?.count||0,candidates:(data?.recordings||[]).map((r:any)=>({id:r.id,title:plain(r.title),artist:(r['artist-credit']||[]).map((a:any)=>plain(a.name)+plain(a.joinphrase)).join(''),version:plain(r.disambiguation),release:plain(r['first-release-date']),source:'https://musicbrainz.org/recording/'+r.id}))}})}
export async function releases(recording:string){uuid.parse(recording);return cached('releases',recording,async()=>{const data=await mb('release?'+new URLSearchParams({recording,fmt:'json',inc:'artist-credits',limit:'100'}));return {candidates:(data?.releases||[]).map((r:any)=>({id:r.id,title:plain(r.title),date:plain(r.date),country:plain(r.country),status:plain(r.status),version:plain(r.disambiguation),source:'https://musicbrainz.org/release/'+r.id}))}})}
export async function covers(release:string){uuid.parse(release);return cached('covers',release,async()=>{const data=await fetchJson('https://coverartarchive.org/release/'+release+'/', ['coverartarchive.org','archive.org']);return {candidates:(data?.images||[]).filter((i:any)=>i.front).flatMap((i:any)=>{const url=i.thumbnails?.['500']||i.thumbnails?.['250'];if(!allowedCover(url))return [];return [{id:String(i.id),url,release,source:'https://coverartarchive.org/release/'+release+'/',front:true}]})}})}
export function allowedCover(url:unknown){try{const u=new URL(String(url));return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&(u.hostname==='coverartarchive.org'||u.hostname==='archive.org'||/^(?:ia|dn)[0-9]+\.(?:[a-z]{2}\.)?archive\.org$/.test(u.hostname))}catch{return false}}
export async function previewVideo(input:string){const url=youtube(input);if(!url)throw new AppError('INVALID_INPUT','영상 주소를 입력해 주세요.');try{const result=await cached('youtube',url,async()=>{const data=await fetchJson('https://www.youtube.com/oembed?'+new URLSearchParams({url,format:'json'}),['www.youtube.com'],{},131072,5000);if(!data)return {preview:null};let thumbnail=null;try{const t=new URL(data.thumbnail_url);if(t.protocol==='https:'&&['i.ytimg.com','img.youtube.com'].includes(t.hostname))thumbnail=t.href}catch{}return {preview:{title:plain(data.title),channel:plain(data.author_name),thumbnail,queriedAt:new Date().toISOString()}}},3600);return {normalizedUrl:url,previewStatus:result.preview?'loaded':'not_loaded',preview:result.preview}}catch(e){if(e instanceof AppError&&e.code==='PROVIDER_DISABLED')throw e;return {normalizedUrl:url,previewStatus:'not_loaded',preview:null}}}
export async function candidate(lookupId:string,candidateId:string,provider:string){const {data,error}=await serviceDb().from('songbook_lookup_cache').select('data').eq('id',lookupId).eq('provider',provider).gt('expires_at',new Date().toISOString()).maybeSingle();dbError(error);const c=data?.data?.candidates?.find((x:any)=>x.id===candidateId);if(!c)throw new AppError('LOOKUP_EXPIRED','검색 결과가 만료되었습니다. 다시 조회해 주세요.',409);return c}
export async function verifyTurnstile(token:string,key:string){const data=await fetchJson('https://challenges.cloudflare.com/turnstile/v0/siteverify',['challenges.cloudflare.com'],{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({secret:env('TURNSTILE_SECRET_KEY'),response:token,idempotency_key:key})},16384,7000);if(!data?.success||data.action!=='photo-request'||data.hostname!==new URL(env('SITE_ORIGIN')).hostname)throw new AppError('CAPTCHA_FAILED','보안 확인이 만료되었거나 실패했습니다. 다시 확인해 주세요.')}
export type LiveSnapshot={status:'live'|'offline'|'unknown';title:string|null;thumbnailUrl:string|null;channelUrl:string;broadcastUrl:string|null;lastAttemptAt:string|null;lastSuccessAt:string|null;isStale:boolean};
export async function liveStatus():Promise<LiveSnapshot>{const channel=process.env.SOOP_CHANNEL_ID||'bomyangul',channelUrl='https://www.sooplive.com/station/'+encodeURIComponent(channel),unknown:LiveSnapshot={status:'unknown',title:null,thumbnailUrl:null,channelUrl,broadcastUrl:null,lastAttemptAt:null,lastSuccessAt:null,isStale:true};if(process.env.LIVE_INTEGRATIONS_ENABLED!=='true'||process.env.VERCEL_ENV==='preview')return unknown;const db=serviceDb();const {data:cache}=await db.from('broadcast_cache').select('*').eq('id',true).single();if(cache?.last_success_at&&Date.now()-Date.parse(cache.last_success_at)<60000)return {...cache.data,lastAttemptAt:cache.last_attempt_at,lastSuccessAt:cache.last_success_at,isStale:false};if(!await rpc<boolean>(db,'claim_live_lease'))return {...unknown,lastAttemptAt:cache?.last_attempt_at||null,lastSuccessAt:cache?.last_success_at||null};const at=new Date().toISOString();try{if(!/^[A-Za-z0-9_-]+$/.test(channel))throw Error();const data=await fetchJson('https://chapi.sooplive.co.kr/api/'+channel+'/station',['chapi.sooplive.co.kr'],{},262144,7000);if(!data||!Object.hasOwn(data,'broad'))throw Error();let snap:LiveSnapshot={...unknown,status:'offline',isStale:false,lastAttemptAt:at,lastSuccessAt:at};if(data.broad!==null){const b=data.broad;if(typeof b.broad_title!=='string'||!/^\d+$/.test(String(b.broad_no)))throw Error();let thumbnail:string|null=null;if(typeof b.broad_img==='string'){const t=new URL(b.broad_img.startsWith('//')?'https:'+b.broad_img:b.broad_img);if(t.protocol==='https:'&&/(^|\.)(sooplive\.(com|co\.kr)|afreecatv\.com)$/.test(t.hostname))thumbnail=t.href}snap={...snap,status:'live',title:b.broad_title.slice(0,300),thumbnailUrl:thumbnail,broadcastUrl:'https://play.sooplive.co.kr/'+channel+'/'+b.broad_no}}await db.from('broadcast_cache').update({data:snap,last_success_at:at,lease_until:null}).eq('id',true);return snap}catch{await db.from('broadcast_cache').update({lease_until:null}).eq('id',true);return {...unknown,lastAttemptAt:at,lastSuccessAt:cache?.last_success_at||null}}}
