import 'server-only';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {Site,Song,Category,Signature,Account,LedgerEntry,PhotoRequest} from '@jjosami/shared';
import {AppError,dbError,publicDb,rpc} from './db';
import {boundedPage} from './http';
export async function readSite(db=publicDb(),admin=false){const data=await rpc<Site>(db,'site_read',{p_admin:admin});if(!data?.profile)throw new AppError('SITE_UNAVAILABLE','사이트 정보를 불러오지 못했습니다.',503);return data}
export async function readCategories(db=publicDb(),admin=false):Promise<Category[]>{let q=db.from('song_categories').select('*').order('display_order').order('id');if(!admin)q=q.eq('active',true);const {data,error}=await q;dbError(error);return (data||[]).map(c=>({id:c.id,name:c.name,slug:c.slug,active:c.active,order:c.display_order,version:c.version}))}
export async function readSignatures(params:URLSearchParams,db=publicDb(),admin=false){const {page,size}=boundedPage(params);let q=db.from('signatures').select('*',{count:'exact'});if(!admin)q=q.eq('is_visible',true);const term=(params.get('q')||'').slice(0,200);if(term)q=q.ilike('name','%'+term.replace(/[\\%_]/g,'\\$&')+'%');if(params.get('category'))q=q.eq('category',params.get('category'));const sort=params.get('sort')||'count_asc';q=sort.startsWith('name')?q.order('name',{ascending:sort==='name_asc'}):q.order('balloon_count',{ascending:sort!=='count_desc'});const {data,error,count}=await q.order('display_order').order('id').range((page-1)*size,page*size-1);dbError(error);return {rows:(data||[]).map(s=>({id:s.id,name:s.name,count:s.balloon_count,description:s.description,category:s.category,image:s.image,order:s.display_order,visible:s.is_visible,version:s.version})) as Signature[],total:count||0,page,size}}
export async function readSongs(params:URLSearchParams,db=publicDb(),admin=false){
 const {page,size}=boundedPage(params),sort=params.get('sort')||'title',q=(params.get('q')||'').slice(0,200).normalize('NFKC').toLowerCase();
 const min=params.get('difficultyMinStep'),max=params.get('difficultyMaxStep'),unrated=params.get('unratedOnly')==='true';if(unrated&&(min||max)||min&&(!Number.isInteger(Number(min))||Number(min)<1||Number(min)>10)||max&&(!Number.isInteger(Number(max))||Number(max)<1||Number(max)>10)||min&&max&&Number(min)>Number(max))throw new AppError('INVALID_INPUT','난이도 범위를 확인해 주세요.');
 if(!['title','artist','difficulty_asc','difficulty_desc','newest'].includes(sort))throw new AppError('INVALID_INPUT','정렬 기준을 확인해 주세요.');
 const result=await rpc<{rows:Record<string,unknown>[];total:number}>(db,'search_songs',{p_q:q,p_categories:params.getAll('category'),p_min:min?Number(min):null,p_max:max?Number(max):null,p_unrated:unrated,p_sort:sort,p_page:page,p_size:size,p_admin:admin,p_visibility:admin?(params.get('visibility')||''):''});
 return {rows:result.rows as unknown as Song[],total:result.total,page,size};
}
export async function readAccounts(params:URLSearchParams,db=publicDb()){const {page,size}=boundedPage(params);const result=await rpc<{rows:Account[];total:number}>(db,'read_accounts',{p_q:(params.get('q')||'').slice(0,200),p_type:params.get('type')||null,p_remaining:params.get('remaining')==='true',p_page:page,p_size:size});return {...result,page,size}}
export async function readHistory(account:string,page=1,db=publicDb()){return rpc<LedgerEntry[]>(db,'read_public_history',{p_account:account,p_page:page})}
export async function readRequests(params:URLSearchParams,db:SupabaseClient){const {page,size}=boundedPage(params);let q=db.from('photo_requests').select('*',{count:'exact'}).order('created_at',{ascending:false}).order('id');if(params.get('status'))q=q.eq('status',params.get('status'));if(params.get('from'))q=q.gte('created_at',params.get('from')+'T00:00:00+09:00');if(params.get('to'))q=q.lte('created_at',params.get('to')+'T23:59:59.999+09:00');const term=(params.get('q')||'').slice(0,100);if(term){const safe=term.replace(/[\\%_(),."]/g,'');q=q.or('nickname.ilike.%'+safe+'%,soop_id.ilike.%'+safe+'%')};const {data,error,count}=await q.range((page-1)*size,page*size-1);dbError(error);return {rows:(data||[]).map(r=>({id:r.id,receipt:r.receipt,nickname:r.nickname,soop:r.soop_id,message:r.message,status:r.status,memo:r.memo,accountId:r.account_id,quantity:Number(r.quantity),createdAt:r.created_at,version:r.version})) as PhotoRequest[],total:count||0,page,size}}
