import 'server-only';
import {signedHeaders} from '@jjosami/shared/security';
import {AppError,dbError,env,rpc,serviceDb} from './db';
import {fetchPage,parseCatalog,parseAlertBootstrap,validateUrl} from './integrations/weflab-adapter.mjs';
export {validateUrl};
export async function collectorSettings(){const {data,error}=await serviceDb().from('site_settings').select('data,version').eq('id',true).single();dbError(error);return {catalogUrl:'',alertUrl:'',...data!.data,version:data!.version}}
export function requireLive(){if(process.env.LIVE_INTEGRATIONS_ENABLED!=='true'||process.env.VERCEL_ENV==='preview')throw new AppError('PROVIDER_DISABLED','이 환경에서는 실제 수집이 비활성화되어 있습니다.',503)}
export async function syncCatalog(){requireLive();const settings=await collectorSettings();if(!settings.catalogUrl)throw new AppError('INVALID_INPUT','룰렛 목록 URL을 먼저 저장해 주세요.');if(!await rpc<boolean>(serviceDb(),'claim_provider',{p_key:'weflab-catalog',p_milliseconds:30000}))throw new AppError('PROVIDER_RATE_LIMITED','룰렛 목록을 갱신 중입니다. 잠시 후 다시 시도해 주세요.',429);let catalog;try{catalog=parseCatalog(await fetchPage(settings.catalogUrl,'catalog'))}catch{throw new AppError('PROVIDER_UNAVAILABLE','룰렛 목록을 불러오지 못했습니다. URL과 공개 설정을 확인해 주세요.',503)}const {error}=await serviceDb().from('roulette_catalog').upsert({id:true,data:catalog,version:catalog.version,last_success_at:new Date().toISOString()});dbError(error);return catalog}
export async function controlCollector(action:string,commandId:string){if(action!=='stop'&&action!=='status')requireLive();let identity;if(action==='start'||action==='reconnect'){const s=await collectorSettings();if(!s.alertUrl)throw new AppError('INVALID_INPUT','후원 알림 URL을 먼저 저장해 주세요.');try{identity=parseAlertBootstrap(await fetchPage(s.alertUrl,'alert'))}catch{throw new AppError('PROVIDER_UNAVAILABLE','후원 알림 연결 정보를 읽지 못했습니다.',503)}}const url=new URL(env('COLLECTOR_ORIGIN'));if(url.protocol!=='https:'||url.username||url.password)throw new AppError('SERVICE_UNAVAILABLE','수집기 설정을 확인해 주세요.',503);const body=JSON.stringify({commandId,action,...(identity?{identity}:{})});const response=await fetch(url.origin+'/control',{method:'POST',redirect:'error',headers:await signedHeaders(env('COLLECTOR_CONTROL_SECRET'),'/control',body),body,signal:AbortSignal.timeout(12000)});if(!response.ok)throw new AppError('COLLECTOR_UNAVAILABLE','수집기 요청에 실패했습니다. 연결 설정을 확인해 주세요.',503);return (await response.json()).data}
export async function integrationStatus(){const db=serviceDb();const [settings,catalog,mappings,state,reviews]=await Promise.all([collectorSettings(),db.from('roulette_catalog').select('data,last_success_at').eq('id',true).maybeSingle(),db.from('roulette_mappings').select('*'),db.from('collector_state').select('*').eq('id',true).maybeSingle(),db.from('roulette_events').select('id',{count:'exact',head:true}).eq('status','review_required')]);for(const r of [catalog,mappings,state,reviews])dbError(r.error);return {settings,catalog:catalog.data?.data||null,lastCatalogAt:catalog.data?.last_success_at||null,mappings:mappings.data||[],state:state.data?{...state.data.data,observedAt:state.data.observed_at}:null,reviewCount:reviews.count||0}}
export async function ingestEvents(events:any[]){const db=serviceDb();const {data:catalog}=await db.from('roulette_catalog').select('data').eq('id',true).maybeSingle();const results=[];for(const e of events){const r=e.result;const clean={source:r.source,sourceEventId:r.sourceEventId,drawIndex:r.drawIndex,platform:r.platform,soop:r.soop,nickname:r.nickname,itemName:r.itemName,donation:r.donation,occurredAt:r.occurredAt};const sourceKey=r.sourceEventId&&r.drawIndex!==null?[env('STREAMER_KEY'),e.identityKey,r.platform,r.sourceEventId,r.drawIndex].join(':'):null;let status=r.status,reason=r.reason,mappingKey=null;if(status==='ready'){const matches=(catalog?.data?.groups||[]).flatMap((g:any)=>g.ranges.some((range:any)=>range.platform===r.platform&&r.donation>=range.min&&(range.max===null||r.donation<=range.max))?g.items.filter((i:any)=>i.name===r.itemName).map((i:any)=>g.id+':'+i.id):[]);if(matches.length===1)mappingKey=matches[0];else{status='review_required';reason=matches.length?'여러 룰렛에 같은 결과가 있습니다.':'연결할 룰렛 항목을 찾지 못했습니다.'}}try{results.push(await rpc(db,'ingest_result',{p_receipt:e.receiptId,p_source_key:sourceKey,p_payload:clean,p_mapping_key:mappingKey,p_status:status,p_reason:reason}))}catch{results.push({receiptId:e.receiptId,status:'retry'})}}return {results}}
