import 'server-only';
import sharp from 'sharp';
import {profileSchema,songSchema,type Profile,type Site} from '@jjosami/shared';
import type {SupabaseClient} from '@supabase/supabase-js';
import {AppError,dbError,env,rpc,serviceDb} from './db';
import {candidate} from './providers';
export async function validAssetUrl(url:string){if(url==='/assets/profile.webp')return url;const base=env('SUPABASE_URL')+'/storage/v1/object/public/site-assets/';if(!url.startsWith(base))throw new AppError('INVALID_IMAGE','업로드한 이미지를 선택해 주세요.');const path=url.slice(base.length);const {data}=await serviceDb().from('site_assets').select('id').eq('path',path).maybeSingle();if(!data)throw new AppError('INVALID_IMAGE','이미지를 찾을 수 없습니다. 다시 업로드해 주세요.');return url}
export async function uploadAsset(request:Request,actor:string){if(Number(request.headers.get('content-length'))>3300000)throw new AppError('TOO_LARGE','이미지는 3MB 이하만 등록할 수 있습니다.',413);const reader=request.body?.getReader();if(!reader)throw new AppError('INVALID_IMAGE','파일을 선택해 주세요.');const chunks:Uint8Array[]=[];let size=0;try{while(true){const r=await reader.read();if(r.done)break;size+=r.value.length;if(size>3300000)throw new AppError('TOO_LARGE','이미지는 3MB 이하만 등록할 수 있습니다.',413);chunks.push(r.value)}}finally{await reader.cancel().catch(()=>{})}const bounded=new Response(Buffer.concat(chunks),{headers:{'Content-Type':request.headers.get('content-type')||''}});const form=await bounded.formData(),file=form.get('file');if(!(file instanceof File)||!file.size||file.size>3145728)throw new AppError('INVALID_IMAGE','3MB 이하의 이미지 파일을 선택해 주세요.');const bytes=Buffer.from(await file.arrayBuffer());let m;try{m=await sharp(bytes,{animated:true,limitInputPixels:64000000}).metadata()}catch{throw new AppError('INVALID_IMAGE','유효한 이미지 파일을 선택해 주세요.')}const formats:Record<string,string>={jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif'};if(!m.format||!formats[m.format]||!m.width||!m.height||m.width>8192||m.height/(m.pages||1)>8192||(m.pages||1)>1000)throw new AppError('INVALID_IMAGE','JPEG·PNG·WebP·GIF 이미지와 크기를 확인해 주세요.');const id=crypto.randomUUID(),path=id+'.'+m.format,db=serviceDb();const {error}=await db.storage.from('site-assets').upload(path,bytes,{contentType:formats[m.format],upsert:false,cacheControl:'31536000'});dbError(error);const saved=await db.from('site_assets').insert({id,path,mime:formats[m.format],bytes:file.size,width:m.width,height:m.height,created_by:actor});if(saved.error){await db.storage.from('site-assets').remove([path]);dbError(saved.error)}return {id,url:db.storage.from('site-assets').getPublicUrl(path).data.publicUrl}}
export async function writeProfile(db:SupabaseClient,input:any,key:string){const profile=profileSchema.parse(input.profile);await validAssetUrl(profile.image);const current=await rpc<Site>(db,'site_read',{p_admin:true});const dates=[];for(const f of profile.fields){if(!f.binding)continue;const d=current.anniversaries.find(a=>a.key===f.binding);if(!d){if(f.value)throw new AppError('INVALID_INPUT','연결할 기념일이 없습니다. 캘린더에서 기념일을 먼저 등록해 주세요.');continue}if(f.value){const source=d.type==='annual'&&d.birthYear?d.birthYear+'-'+d.date:d.date;const value=f.value.replaceAll('.','-');const date=d.type==='annual'&&value.length===5?'2000-'+value:value;if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date+'T00:00:00Z').toISOString().slice(0,10)!==date)throw new AppError('INVALID_INPUT',f.label+' 날짜를 확인해 주세요.');dates.push({key:f.binding,date:value,version:input.dateVersions[f.binding]})}f.value=''}return rpc(db,'save_profile',{p_data:profile,p_dates:dates,p_version:input.expectedVersion,p_key:key})}
export async function writeSong(db:SupabaseClient,id:string|null,input:unknown,key:string){const s=songSchema.parse(input);let coverUrl=null,coverSource=null,coverAsset=null,metadata:any={fields:{}};if(id){const old=await db.from('song_admin_metadata').select('metadata').eq('song_id',id).maybeSingle();dbError(old.error);metadata=old.data?.metadata||{fields:{}}}metadata={...metadata,fields:{...metadata.fields}};
 if(s.cover.type==='upload'){const {data,error}=await db.from('site_assets').select('path').eq('id',s.cover.assetId).single();dbError(error);coverAsset=s.cover.assetId;coverUrl=env('SUPABASE_URL')+'/storage/v1/object/public/site-assets/'+data!.path}
 if(s.cover.type==='candidate'){const c=await candidate(s.cover.lookupId,s.cover.candidateId,'covers');coverUrl=c.url;coverSource=c.source;metadata.cover={provider:'coverartarchive',release:c.release,image:c.id,source:c.source}}
 if(s.cover.type==='existing'){if(s.cover.songId!==id)throw new AppError('INVALID_INPUT','현재 곡의 커버만 유지할 수 있습니다.');const {data,error}=await db.from('songs').select('cover_url,cover_source_url,cover_asset_id').eq('id',id).single();dbError(error);coverUrl=data!.cover_url;coverSource=data!.cover_source_url;coverAsset=data!.cover_asset_id}
 let recording:any=null,release:any=null;if(s.metadataSelection){recording=await candidate(s.metadataSelection.lookupId,s.metadataSelection.candidateId,'music');metadata.recording=recording.id;metadata.source=recording.source}if(s.releaseSelection){release=await candidate(s.releaseSelection.lookupId,s.releaseSelection.candidateId,'releases');metadata.release=release.id}for(const [field,value] of Object.entries({title:s.title,artist:s.artist,album:s.album,versionLabel:s.versionLabel,release:s.release})){const r=recording&&({title:recording.title,artist:recording.artist,versionLabel:recording.version,release:recording.release} as any)[field],d=release&&({album:release.title,release:release.date} as any)[field];metadata.fields[field]=release&&value===d?{value,source:release.source}:recording&&value===r?{value,source:recording.source}:metadata.fields[field]?.value===value?metadata.fields[field]:{value,source:'manual'}}if(s.cover.type==='none'||s.cover.type==='upload')metadata.cover={provider:s.cover.type};
 const normalize=(v:string)=>v.normalize('NFKC').trim().replace(/\s+/g,' ').toLowerCase();return rpc(db,'save_song',{p_id:id,p_key:key,p_data:{...s,coverUrl,coverSource,coverAsset,coverAlt:s.album||s.title,metadata,titleSort:normalize(s.title),artistSort:normalize(s.artist),searchText:normalize([s.title,s.artist,s.album].join(' '))}})}
