import {z} from 'zod';
export const uuid=z.string().uuid();
export const text=(max:number)=>z.string().trim().max(max);
export const required=(max:number)=>text(max).min(1,'필수 항목입니다.');
export const https=text(2048).refine(v=>{try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port}catch{return false}},'HTTPS 주소를 입력해 주세요.');
export function youtube(value:string){
 if(!value.trim())return null;let u:URL;try{u=new URL(value.trim())}catch{throw Error('YouTube 영상 주소를 확인해 주세요.')}
 if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.port||!['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(u.hostname))throw Error('YouTube 영상 주소만 등록할 수 있습니다.');
 const id=u.hostname==='youtu.be'&&/^\/[\w-]+\/?$/.test(u.pathname)?u.pathname.split('/')[1]:u.pathname==='/watch'?u.searchParams.get('v'):/^\/(shorts|live)\/[\w-]+\/?$/.test(u.pathname)?u.pathname.split('/')[2]:null;
 if(!/^[\w-]{11}$/.test(id||''))throw Error('영상 ID가 있는 YouTube 주소를 입력해 주세요.');return 'https://www.youtube.com/watch?v='+id;
}
const video=text(2048).transform((v,ctx)=>{try{return youtube(v)}catch(e){ctx.addIssue({code:'custom',message:(e as Error).message});return z.NEVER}});
export const validDate=(s:string)=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;
export const fieldSchema=z.object({id:required(100).regex(/^[\w-]+$/),label:required(40),value:text(1000).default(''),visible:z.boolean(),binding:z.enum(['birthday','debut']).optional()}).strict();
export const profileSchema=z.object({name:required(100),short:text(300),bio:text(1500),image:text(2048),alt:text(200),channel:https,fields:z.array(fieldSchema).max(40)}).strict().superRefine((p,ctx)=>{const names=p.fields.map(f=>f.label.normalize('NFKC').toLowerCase()),ids=p.fields.map(f=>f.id),bindings=p.fields.flatMap(f=>f.binding?[f.binding]:[]);if(new Set(names).size!==names.length||new Set(ids).size!==ids.length||new Set(bindings).size!==bindings.length)ctx.addIssue({code:'custom',message:'중복된 프로필 항목을 확인해 주세요.'})});
export const anniversarySchema=z.object({id:uuid.optional(),key:z.enum(['birthday','debut']).nullable().optional(),name:required(100),type:z.enum(['annual','debut','once','schedule']),date:required(10),birthYear:text(4).optional(),time:text(5).regex(/^$|^(?:[01]\d|2[0-3]):[0-5]\d$/),note:text(1000),visible:z.boolean(),order:z.number().int().min(0).max(10000),expectedVersion:z.number().int().positive().optional()}).strict().superRefine((v,ctx)=>{if(!validDate(v.type==='annual'?'2000-'+v.date:v.date))ctx.addIssue({code:'custom',message:'날짜를 확인해 주세요.'});if(v.birthYear&&(!/^\d{4}$/.test(v.birthYear)||Number(v.birthYear)<1900||!validDate(v.birthYear+'-'+v.date)))ctx.addIssue({code:'custom',message:'생년과 날짜를 확인해 주세요.'})});
export const signatureSchema=z.object({name:required(100),count:z.number().int().positive().max(100000000),description:text(1000),category:text(50),order:z.number().int().min(0),image:required(2048),visible:z.boolean(),expectedVersion:z.number().int().positive().optional()}).strict();
export const songSchema=z.object({title:required(200),artist:required(200),album:text(200),versionLabel:text(200),release:text(10).refine(v=>!v||/^\d{4}(-(?:0[1-9]|1[0-2]))?$/.test(v)||validDate(v),'발매일을 확인해 주세요.'),steps:z.number().int().min(1).max(10).nullable(),note:text(200),memo:text(1000),categories:z.array(required(50)).max(30),original:video,karaoke:video,sameVideoConfirmed:z.boolean().default(false),duplicateConfirmed:z.boolean().default(false),cover:z.discriminatedUnion('type',[z.object({type:z.literal('none')}),z.object({type:z.literal('upload'),assetId:uuid}),z.object({type:z.literal('candidate'),lookupId:uuid,candidateId:required(200)}),z.object({type:z.literal('existing'),songId:uuid})]),coverUsageBasis:text(1000),releaseSelection:z.object({lookupId:uuid,candidateId:uuid}).nullable().default(null),metadataSelection:z.object({lookupId:uuid,candidateId:required(100)}).nullable().default(null),visible:z.boolean(),expectedVersion:z.number().int().positive().optional()}).strict().superRefine((s,ctx)=>{if(s.original&&s.original===s.karaoke&&!s.sameVideoConfirmed)ctx.addIssue({code:'custom',message:'원곡과 노래방에 같은 영상이 선택되어 있습니다. 확인 후 저장해 주세요.'});if(s.cover.type==='candidate'&&!s.coverUsageBasis)ctx.addIssue({code:'custom',message:'외부 커버의 공개 사용 근거를 입력해 주세요.'})});
export const requestSchema=z.object({nickname:required(100),soop:required(100),message:text(1000),token:required(2048)}).strict();
export const entrySchema=z.object({nickname:required(100),soop:required(100),typeId:uuid,quantity:z.number().finite().refine(v=>Math.abs(v)<=99999999999&&Math.abs(v*1000-Math.round(v*1000))<1e-5,'수량은 소수점 셋째 자리까지 입력해 주세요.'),kind:z.enum(['acquire','adjust','fulfill','invalidate','set']),reason:required(500),expectedVersion:z.number().int().nonnegative().optional()}).strict().refine(v=>v.kind==='set'?v.quantity>=0:v.quantity!==0,'수량을 확인해 주세요.');
export const requestEditSchema=z.object({status:z.enum(['received','reviewing','in_progress','completed','on_hold','cancelled']),memo:text(1000),accountId:uuid.nullable(),quantity:z.number().positive().max(99999999999),verified:z.boolean(),confirmed:z.boolean(),reason:text(500),expectedVersion:z.number().int().positive()}).strict();
export type Profile=z.infer<typeof profileSchema>;
export type Anniversary=Omit<z.infer<typeof anniversarySchema>,'id'|'expectedVersion'> & {id:string;version:number};
export type Signature=z.infer<typeof signatureSchema>&{id:string;version:number};
export type Song={id:string;title:string;artist:string;album:string;versionLabel:string;release:string;steps:number|null;note:string;memo?:string;categories:string[];original:string|null;karaoke:string|null;cover:string|null;coverAlt:string;coverSource:string|null;coverUsageBasis?:string;visible:boolean;version:number;createdAt:string};
export type Category={id:string;name:string;slug:string;active:boolean;order:number;version:number};
export type Site={profile:Profile;anniversaries:Anniversary[];version:number};
export type Account={id:string;soop:string;nickname:string;typeId:string;item:string;unit:string;integer:boolean;acquired:number;adjusted:number;fulfilled:number;balance:number;version:number};
export type LedgerEntry={id:string;accountId:string;delta:number;kind:string;time:string;reason?:string;reversed:boolean};
export type PhotoRequest={id:string;receipt:string;nickname:string;soop:string;message:string;status:string;memo:string;accountId:string|null;quantity:number;createdAt:string;version:number};
export const initialProfile:Profile={name:'쪼삼이',short:'장난기 많은데 정 붙으면 엄청 편한 타입',bio:'초면에도 잘 놀아요, 다만 오냐오냐해줘야합니다…',image:'/assets/profile.webp',alt:'쪼삼이 대표 이미지',channel:'https://www.sooplive.com/station/bomyangul',fields:[{id:'debut',label:'방송 시작',value:'',binding:'debut',visible:true},{id:'birthday',label:'생일',value:'',binding:'birthday',visible:true},{id:'height',label:'키',value:'168cm',visible:true},{id:'mbti',label:'MBTI',value:'INFP',visible:true},{id:'likes',label:'좋아해요',value:'놀리는거, 디저트류, 방송장비, 예쁜 언니야들, 사랑받기',visible:true},{id:'dislikes',label:'싫어해요',value:'놀림받는거, 공포게임, 똥겜, 질투유발하는 무언가, 벌레',visible:true},{id:'wish',label:'하고싶어요',value:'모두에게 사랑받는 사랑둥이 막내가 되고싶어요!',visible:true},{id:'fan',label:'팬덤명',value:'미정',visible:true}]};
export const koreanDate=(now=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);
export function occurrence(a:Pick<Anniversary,'date'|'type'>,year:number){if(!['annual','debut'].includes(a.type))return a.date;if(a.type==='debut'&&year<Number(a.date.slice(0,4)))return '';const [m,d]=a.date.slice(-5).split('-').map(Number);return `${year}-${String(m).padStart(2,'0')}-${String(Math.min(d,new Date(Date.UTC(year,m,0)).getUTCDate())).padStart(2,'0')}`}
export function countdown(a:Pick<Anniversary,'date'|'type'>,today=koreanDate()){let target=a.date;if(a.type==='annual'){target=occurrence(a,Number(today.slice(0,4)));if(target<today)target=occurrence(a,Number(today.slice(0,4))+1)}const diff=Math.round((Date.parse(target)-Date.parse(today))/86400000);return a.type==='debut'?(diff<=0?'D+'+(1-diff):'D-'+diff):diff===0?'D-Day':diff<0?'종료':'D-'+diff}
export function resolvedFields(profile:Profile,dates:Anniversary[]){return profile.fields.flatMap(f=>{if(!f.visible)return [];if(!f.binding)return f.value.trim()?[f]:[];const d=dates.find(d=>d.key===f.binding&&d.visible);if(!d)return [];const full=d.type==='annual'&&d.birthYear?d.birthYear+'-'+d.date:d.date;return [{...f,value:(validDate(full)?full:d.date).replaceAll('-','.')}]})}
export function csvCell(v:unknown){let s=String(v??'');if(/^[\s\u0000-\u001f]*[=+\-@]/.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
export const transitions:Record<string,string[]>={received:['reviewing','on_hold','cancelled'],reviewing:['in_progress','on_hold','cancelled'],in_progress:['completed','on_hold','cancelled'],on_hold:['reviewing','cancelled'],completed:['reviewing'],cancelled:['reviewing']};
export const statuses:Record<string,string>={received:'접수 완료',reviewing:'확인 중',in_progress:'작업 중',completed:'처리 완료',on_hold:'보류',cancelled:'취소'};

export {z};
