import {readFile,writeFile,readdir,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {zipSync,unzipSync,strToU8} from 'fflate';
const root=path.resolve(import.meta.dirname,'..'),files=[];
const directories=['apps/web/src','apps/web/public','packages/shared/src','workers/collector/src','supabase/migrations','licenses'];
const individual=['README.md','DEPLOYMENT.md','OPERATIONS.md','VALIDATION.md','package.json','pnpm-lock.yaml','pnpm-workspace.yaml','tsconfig.base.json','.nvmrc','.gitignore','apps/web/package.json','apps/web/tsconfig.json','apps/web/next.config.ts','apps/web/next-env.d.ts','apps/web/.env.example','packages/shared/package.json','packages/shared/tsconfig.json','workers/collector/package.json','workers/collector/tsconfig.json','workers/collector/wrangler.jsonc','workers/collector/worker-configuration.d.ts','workers/collector/.dev.vars.example','supabase/config.toml','scripts/grant-admin.sql','scripts/healthcheck.mjs','scripts/release.mjs'];
async function visit(dir){for(const entry of await readdir(path.join(root,dir),{withFileTypes:true})){if(entry.isSymbolicLink())throw Error('Symlink excluded: '+entry.name);const rel=dir+'/'+entry.name;if(entry.isDirectory())await visit(rel);else files.push(rel)}}
for(const dir of directories)await visit(dir);files.push(...individual);const entries={},manifest=[];
for(const rel of [...new Set(files)].sort()){if(/(?:^|\/)(?:AGENTS|CLAUDE|SKILL|DESIGN|PRODUCT)\.md$|(?:^|\/)\.env(?!\.example$)|(?:^|\/)\.dev\.vars(?!\.example$)|node_modules|\.local\//i.test(rel))throw Error('Forbidden release file: '+rel);let bytes=await readFile(path.join(root,rel));if(rel==='package.json'){const pkg=JSON.parse(bytes);delete pkg.scripts.test;bytes=Buffer.from(JSON.stringify(pkg,null,2)+'\n')}if(/\.(ts|tsx|js|mjs|sql|md|json|jsonc|yaml|example)$/.test(rel)&&new RegExp(["lOPU2"+"suXmg","guPK2"+"ODAmGg","local-test-"+"password-only","sb_secret_"+"[A-Za-z0-9]+","SUPABASE_SECRET_"+"KEY="+"\\S+"].join("|")).test(bytes.toString()))throw Error('Fixture or credential found: '+rel);entries['jjosami-site/'+rel]=new Uint8Array(bytes);manifest.push({path:rel,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')})}
entries['jjosami-site/RELEASE-MANIFEST.json']=strToU8(JSON.stringify({version:'1.0.0',createdAt:new Date().toISOString(),files:manifest},null,2));const zip=zipSync(entries,{level:9}),verified=unzipSync(zip);for(const f of manifest){const data=verified['jjosami-site/'+f.path];if(!data||createHash('sha256').update(data).digest('hex')!==f.sha256)throw Error('Archive verification failed: '+f.path)}
const out=path.resolve(root,'../releases');await mkdir(out,{recursive:true});const name='jjosami-production-1.0.0.zip';await writeFile(path.join(out,name),zip);await writeFile(path.join(out,name+'.sha256'),createHash('sha256').update(zip).digest('hex')+'  '+name+'\n');console.log(JSON.stringify({path:path.join(out,name),files:manifest.length,bytes:zip.length,verified:true},null,2));
