import {z,uuid,signatureSchema,anniversarySchema,requestSchema,entrySchema,requestEditSchema,csvCell} from '@jjosami/shared';
import {verifySignature} from '@jjosami/shared/security';
import {AppError,dbError,env,publicDb,requireAdmin,rpc,serviceDb,sessionDb} from '@/server/db';
import {boundedPage,failure,jsonBody,operationKey,rateLimit,rawBody,sameOrigin,success} from '@/server/http';
import {readAccounts,readCategories,readHistory,readRequests,readSignatures,readSite,readSongs} from '@/server/read';
import {covers,liveStatus,musicSearch,previewVideo,releases,verifyTurnstile} from '@/server/providers';
import {controlCollector,ingestEvents,integrationStatus,requireLive,syncCatalog,validateUrl} from '@/server/weflab';
import {uploadAsset,validAssetUrl,writeProfile,writeSong} from '@/server/write';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=30;
async function handle(req:Request){try{const url=new URL(req.url),path=url.pathname.replace(/^\/api\//,''),parts=path.split('/'),s=url.searchParams,m=req.method;
 if(path.startsWith('internal/weflab/')&&m==='POST'){
  const body=await rawBody(req);if(!await verifySignature(env('COLLECTOR_INGEST_SECRET'),req.headers,m,url.pathname,body))throw new AppError('UNAUTHORIZED','인증되지 않은 요청입니다.',401);requireLive();const input=JSON.parse(body);
  if(path==='internal/weflab/events'){const event=z.object({receiptId:uuid,streamerKey:z.literal(env('STREAMER_KEY')),identityKey:z.string().min(1).max(200),result:z.object({source:z.literal('weflab'),sourceEventId:z.string().max(300).nullable(),drawIndex:z.number().int().min(0).max(199).nullable(),platform:z.string().max(30),soop:z.string().max(100),nickname:z.string().max(100),itemName:z.string().max(200),donation:z.number().finite().positive().nullable(),occurredAt:z.string().max(100).nullable(),receivedAt:z.string().datetime(),status:z.enum(['ready','review_required','ignored']),reason:z.string().max(500)})});const parsed=z.object({schemaVersion:z.literal(1),events:z.array(event).max(50)}).parse(input);return success(await ingestEvents(parsed.events))}
  if(path==='internal/weflab/state'){const parsed=z.object({state:z.object({running:z.boolean(),connection:z.string().max(30),lastHeartbeatAt:z.string().nullable(),lastEventAt:z.string().nullable(),lastDbSuccessAt:z.string().nullable(),pendingCount:z.number().int().min(0),reconnects:z.number().int().min(0),lastError:z.string().max(500).nullable(),lastCatalogError:z.string().max(500).nullable().optional(),gaps:z.array(z.object({started:z.number(),ended:z.number().nullable()})).max(20)}),observedAt:z.string().datetime()}).parse(input);if(Math.abs(Date.now()-Date.parse(parsed.observedAt))>300000)throw new AppError('INVALID_INPUT','관측 시각이 유효하지 않습니다.');await rpc(serviceDb(),'update_collector_state',{p_data:parsed.state,p_observed:parsed.observedAt});return success({stored:true})}
  if(path==='internal/weflab/catalog/sync')return success(await syncCatalog());
 }
 if(path==='auth/login'&&m==='POST'){sameOrigin(req);await rateLimit(req,'login',10,600);const input=z.object({email:z.string().email().max(254),password:z.string().min(1).max(256)}).strict().parse(await jsonBody(req));const db=await sessionDb(true);const {error}=await db.auth.signInWithPassword(input);if(error)throw new AppError('LOGIN_FAILED','이메일 또는 비밀번호를 확인해 주세요.',401);try{await requireAdmin()}catch{await db.auth.signOut();throw new AppError('FORBIDDEN','관리자 권한이 없습니다.',403)}return success({authenticated:true})}
 if(path==='auth/logout'&&m==='POST'){sameOrigin(req);const db=await sessionDb(true);await db.auth.signOut();return success({authenticated:false})}
 if(path==='auth/session'&&m==='GET'){const {user}=await requireAdmin();return success({authenticated:true,email:user.email})}
 if(path==='site'&&m==='GET')return success(await readSite());
 if(path==='live'&&m==='GET')return success(await liveStatus());
 if(path==='signatures'&&m==='GET')return success(await readSignatures(s));
 if(path==='songs'&&m==='GET')return success(await readSongs(s));
 if(path==='song-categories'&&m==='GET')return success(await readCategories());
 if(path==='obligations'&&m==='GET'){if(s.get('type'))uuid.parse(s.get('type'));return success(await readAccounts(s))}
 if(parts[0]==='obligations'&&parts[2]==='history'&&m==='GET'){uuid.parse(parts[1]);return success(await readHistory(parts[1],boundedPage(s).page))}
 if(path==='requests'&&m==='POST'){sameOrigin(req);const input=requestSchema.parse(await jsonBody(req)),key=operationKey(req),data={nickname:input.nickname,soop:input.soop,message:input.message};await rateLimit(req,'request-retry',30,60);const prior=await rpc(serviceDb(),'request_retry',{p_key:key,p_data:data});if(prior)return success(prior);await rateLimit(req,'request',5,600);await verifyTurnstile(input.token,key);return success(await rpc(serviceDb(),'submit_request',{p_data:data,p_key:key}))}
 if(parts[0]!=='admin')throw new AppError('NOT_FOUND','페이지를 찾을 수 없습니다.',404);
 const {db,user}=await requireAdmin();if(m!=='GET')sameOrigin(req);await rateLimit(req,'admin',180,60,user.id);
 const type=parts[1],id=parts[2];
 if(type==='profile'){if(m==='GET')return success(await readSite(db,true));if(m==='PATCH')return success(await writeProfile(db,z.object({profile:z.unknown(),expectedVersion:z.number().int().positive(),dateVersions:z.record(z.string(),z.number().int().positive())}).strict().parse(await jsonBody(req)),operationKey(req)))}
 if(type==='assets'&&m==='POST')return success(await uploadAsset(req,user.id));
 if(type==='anniversaries'){if(m==='GET')return success((await readSite(db,true)).anniversaries);if(id)uuid.parse(id);if(m==='POST'||m==='PATCH'){const input=anniversarySchema.parse(await jsonBody(req));if(id&&!input.expectedVersion)throw new AppError('INVALID_INPUT','수정 버전이 필요합니다.');return success(await rpc(db,'save_anniversary',{p_id:id||null,p_data:input,p_key:operationKey(req)}))}if(m==='DELETE'){const data=z.object({expectedVersion:z.number().int().positive()}).parse(await jsonBody(req));return success(await rpc(db,'delete_anniversary',{p_id:uuid.parse(id),p_version:data.expectedVersion,p_key:operationKey(req)}))}}
 if(type==='signatures'){if(m==='GET')return success(await readSignatures(s,db,true));if(id)uuid.parse(id);if(m==='POST'||m==='PATCH'){const input=signatureSchema.parse(await jsonBody(req));await validAssetUrl(input.image);if(id&&!input.expectedVersion)throw new AppError('INVALID_INPUT','수정 버전이 필요합니다.');return success(await rpc(db,'save_signature',{p_id:id||null,p_data:input,p_key:operationKey(req)}))}}
 if(type==='songs'){if(m==='GET')return success(await readSongs(s,db,true));if(id)uuid.parse(id);if(m==='POST'||m==='PATCH')return success(await writeSong(db,id||null,await jsonBody(req),operationKey(req)))}
 if(type==='song-categories'){if(m==='GET')return success(await readCategories(db,true));if(id)uuid.parse(id);if(['POST','PATCH','DELETE'].includes(m)){const input=z.object({name:z.string().trim().min(1).max(50).optional(),active:z.boolean().optional(),order:z.number().int().min(0).optional(),expectedVersion:z.number().int().positive().optional(),targetId:uuid.nullable().optional()}).strict().parse(await jsonBody(req));if(id&&!input.expectedVersion||m!=='DELETE'&&parts[3]!=='reassign'&&(!input.name||input.active===undefined))throw new AppError('INVALID_INPUT','분류 입력 내용을 확인해 주세요.');if(input.targetId===id)throw new AppError('INVALID_INPUT','다른 분류를 선택해 주세요.');return success(await rpc(db,'manage_category',{p_id:id||null,p_data:{...input,action:m==='DELETE'?'delete':parts[3]==='reassign'?'reassign':'save'},p_key:operationKey(req)}))}}
 if(type==='songbook'){await rateLimit(req,'lookup',40,60,user.id);if(m==='GET'&&id==='search'&&parts[3]==='music'){const title=z.string().trim().min(1).max(200).parse(s.get('title')),artist=z.string().max(200).parse(s.get('artist')||''),offset=z.coerce.number().int().min(0).max(1000).parse(s.get('offset')||0);return success(await musicSearch(title,artist,offset))}if(m==='GET'&&id==='recordings'&&parts[4]==='releases')return success(await releases(uuid.parse(parts[3])));if(m==='GET'&&id==='covers')return success(await covers(uuid.parse(parts[3])));if(m==='POST'&&id==='youtube'&&parts[3]==='preview'){const input=z.object({url:z.string().max(2048)}).strict().parse(await jsonBody(req));return success(await previewVideo(input.url))}}
 if(type==='requests'){if(m==='DELETE'){const input=z.object({expectedVersion:z.number().int().positive()}).strict().parse(await jsonBody(req));return success(await rpc(db,'delete_photo_request',{p_id:uuid.parse(id),p_version:input.expectedVersion,p_key:operationKey(req)}))}if(m==='GET')return success(await readRequests(s,db));if(m==='PATCH'||m==='POST'){uuid.parse(id);const input=requestEditSchema.parse(await jsonBody(req));const current=await db.from('photo_requests').select('status').eq('id',id).single();dbError(current.error);if(input.status==='completed'&&current.data?.status!=='completed'&&parts[3]!=='complete'||parts[3]==='complete'&&input.status!=='completed'||current.data?.status==='completed'&&input.status!=='completed'&&parts[3]!=='reopen')throw new AppError('INVALID_INPUT','완료·재처리 경로를 확인해 주세요.');return success(await rpc(db,'edit_request',{p_id:id,p_data:input,p_key:operationKey(req)}))}}
 if(type==='obligation-types'){if(m==='GET'){const r=await db.from('obligation_types').select('*').order('name');dbError(r.error);return success(r.data)}if(m==='POST'||m==='PATCH'){if(id)uuid.parse(id);const data=z.object({name:z.string().trim().min(1).max(100),unit:z.string().trim().min(1).max(20),integer:z.boolean(),active:z.boolean()}).strict().parse(await jsonBody(req));return success(await rpc(db,'save_obligation_type',{p_id:id||null,p_data:data}))}}
 if(type==='obligations'){
  if(m==='DELETE'){const input=z.object({expectedVersion:z.number().int().nonnegative()}).strict().parse(await jsonBody(req));return success(await rpc(db,'delete_obligation',{p_id:uuid.parse(id),p_version:input.expectedVersion,p_key:operationKey(req)}))}
  if(m==='GET'&&!id)return success(await readAccounts(s,db));
  if(m==='GET'&&id==='ledger'){let q=db.from('obligation_ledger').select('*',{count:'exact'}).order('created_at',{ascending:false});if(s.get('account'))q=q.eq('account_id',uuid.parse(s.get('account')));if(s.get('from'))q=q.gte('created_at',s.get('from')+'T00:00:00+09:00');if(s.get('to'))q=q.lte('created_at',s.get('to')+'T23:59:59.999+09:00');const {page,size}=boundedPage(s);const r=await q.range((page-1)*size,page*size-1);dbError(r.error);return success({rows:r.data,total:r.count,page,size})}
  if(m==='GET'&&id==='export'){const exportParams=new URLSearchParams(s);exportParams.set('pageSize','100');exportParams.set('page','1');const {rows,total}=await readAccounts(exportParams,db);const all=[...rows];for(let page=2;all.length<total&&page<=100;page++){const next=new URLSearchParams(s);next.set('pageSize','100');next.set('page',String(page));all.push(...(await readAccounts(next,db)).rows)}if(all.length<total)throw new AppError('EXPORT_TOO_LARGE','검색 조건을 좁혀 10,000개 이하로 내려받아 주세요.');const csv='\ufeff'+[['닉네임','아이디','항목','단위','획득','조정','이행','잔여'],...all.map(a=>[a.nickname,a.soop,a.item,a.unit,a.acquired,a.adjusted,a.fulfilled,a.balance])].map(row=>row.map(csvCell).join(',')).join('\r\n');return new Response(csv,{headers:{'Content-Type':'text/csv;charset=utf-8','Content-Disposition':'attachment; filename="obligations.csv"','Cache-Control':'no-store'}})}
  if(m==='POST'&&id==='entries'){if(parts[4]==='reverse'){const input=z.object({reason:z.string().trim().min(1).max(500),expectedVersion:z.number().int().nonnegative()}).strict().parse(await jsonBody(req));return success(await rpc(db,'reverse_entry',{p_id:uuid.parse(parts[3]),p_reason:input.reason,p_version:input.expectedVersion,p_key:operationKey(req)}))}return success(await rpc(db,'write_entry',{p_data:entrySchema.parse(await jsonBody(req)),p_key:operationKey(req)}))}
 }
 if(type==='collector'){if(m==='GET')return success(await integrationStatus());if(id==='settings'&&m==='PATCH'){const input=z.object({catalogUrl:z.string().max(2048),alertUrl:z.string().max(2048),expectedVersion:z.number().int().positive()}).strict().parse(await jsonBody(req));try{if(input.catalogUrl)input.catalogUrl=validateUrl(input.catalogUrl,'catalog');if(input.alertUrl)input.alertUrl=validateUrl(input.alertUrl,'alert')}catch(e){throw new AppError('INVALID_INPUT',(e as Error).message)}return success(await rpc(db,'save_settings',{p_data:{catalogUrl:input.catalogUrl,alertUrl:input.alertUrl},p_version:input.expectedVersion}))}if(id==='control'&&m==='POST'){const input=z.object({action:z.enum(['start','stop','reconnect','status'])}).strict().parse(await jsonBody(req));return success(await controlCollector(input.action,operationKey(req)))}}
 if(type==='roulette'){if(id==='catalog'&&parts[3]==='sync'&&m==='POST')return success(await syncCatalog());if(id==='mappings'&&m==='PATCH'){const input=z.object({typeId:uuid.nullable(),quantity:z.number().positive().max(99999999999).nullable(),ignore:z.boolean()}).strict().parse(await jsonBody(req));const key=z.string().regex(/^[a-f0-9]{24}:[a-f0-9]{24}$/).parse(decodeURIComponent(parts[3]));return success(await rpc(db,'save_mapping',{p_key:key,p_type:input.typeId,p_quantity:input.quantity,p_ignore:input.ignore}))}if(id==='reviews'){if(m==='GET'){const {page,size}=boundedPage(s);const r=await db.from('roulette_events').select('*',{count:'exact'}).eq('status','review_required').order('received_at',{ascending:false}).range((page-1)*size,page*size-1);dbError(r.error);return success({rows:r.data,total:r.count,page,size})}if(m==='POST'&&parts[4]==='resolve'){const input=z.object({ignore:z.boolean(),verified:z.boolean(),reason:z.string().trim().max(500).default(''),nickname:z.string().trim().max(100),soop:z.string().trim().max(100),typeId:uuid.nullable(),quantity:z.number().positive().max(99999999999)}).strict().parse(await jsonBody(req));if(!input.ignore&&(!input.soop||!input.nickname||!input.typeId))throw new AppError('INVALID_INPUT','사용자와 업보 항목을 확인해 주세요.');return success(await rpc(db,'resolve_event',{p_id:uuid.parse(parts[3]),p_data:input,p_key:operationKey(req)}))}}}
 throw new AppError('NOT_FOUND','요청한 기능을 찾을 수 없습니다.',404);
 }catch(e){return failure(e)}}
export {handle as GET,handle as POST,handle as PATCH,handle as DELETE};
