create function public.save_settings(p_data jsonb,p_version integer) returns jsonb language plpgsql security definer set search_path='' as $$begin perform public.assert_admin();update public.site_settings set data=p_data,version=version+1 where id=true and version=p_version;if not found then raise exception 'VERSION_CONFLICT' using errcode='40001';end if;perform public.audit('settings.save','site');return jsonb_build_object('version',p_version+1);end$$;
create function public.save_mapping(p_key text,p_type uuid,p_quantity numeric,p_ignore boolean) returns jsonb language plpgsql security definer set search_path='' as $$begin perform public.assert_admin();if not p_ignore then perform 1 from public.obligation_types where id=p_type and active and (not integer_only or p_quantity=trunc(p_quantity));if not found or p_quantity<=0 then raise exception 'INVALID_QUANTITY';end if;end if;insert into public.roulette_mappings(key,type_id,quantity,ignore) values(p_key,case when p_ignore then null else p_type end,case when p_ignore then null else p_quantity end,p_ignore) on conflict(key) do update set type_id=excluded.type_id,quantity=excluded.quantity,ignore=excluded.ignore;perform public.audit('mapping.save',p_key);return jsonb_build_object('key',p_key);end$$;
create function public.ingest_result(p_receipt uuid,p_source_key text,p_payload jsonb,p_mapping_key text,p_status text,p_reason text) returns jsonb language plpgsql security definer set search_path='' as $$declare e public.roulette_events;m public.roulette_mappings;a uuid;i uuid;h text:=encode(sha256(convert_to(p_payload::text,'UTF8')),'hex');s text:=p_status;begin
 perform pg_advisory_xact_lock(hashtextextended(coalesce(p_source_key,p_receipt::text),0));select * into e from public.roulette_events where receipt_id=p_receipt or (p_source_key is not null and source_key=p_source_key) order by (receipt_id=p_receipt) desc limit 1;
 if found then if e.payload_hash=h then return jsonb_build_object('receiptId',p_receipt,'id',e.id,'status',case when e.receipt_id=p_receipt then e.status else 'duplicate' end);end if;if e.receipt_id=p_receipt then raise exception 'RECEIPT_CONFLICT' using errcode='23505';end if;p_source_key=null;s='review_required';p_reason='같은 원본 이벤트의 내용이 달라 확인이 필요합니다.';end if;
 if s not in ('ready','review_required','ignored') then s='review_required';end if;
 if s='ready' then select * into m from public.roulette_mappings where key=p_mapping_key for share;if not found then s='review_required';p_reason='업보 항목 연결이 필요합니다.';elsif m.ignore then s='ignored';else s='applied';end if;end if;
 if s='applied' and (p_source_key is null or nullif(p_payload->>'soop','') is null or nullif(p_payload->>'nickname','') is null) then s='review_required';p_reason='고유 이벤트·후원자 식별자를 확인해 주세요.';end if;
 insert into public.roulette_events(receipt_id,source_key,payload,payload_hash,status,reason) values(p_receipt,p_source_key,p_payload,h,s,p_reason) returning id into i;
 if s='applied' then a=public.ensure_account(p_payload->>'soop',p_payload->>'nickname',m.type_id);perform public.append_ledger(a,m.quantity,'roulette',p_payload->>'itemName',i);end if;
 return jsonb_build_object('receiptId',p_receipt,'id',i,'status',s);end$$;
create function public.resolve_event(p_id uuid,p_data jsonb,p_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare r jsonb;e public.roulette_events;a uuid;begin perform public.assert_admin();r=public.operation_begin('event.resolve',p_key,jsonb_build_object('id',p_id,'data',p_data));if r is not null then return r;end if;select * into e from public.roulette_events where id=p_id for update;if not found or e.status<>'review_required' then raise exception 'REVIEW_ALREADY_RESOLVED' using errcode='40001';end if;if length(trim(p_data->>'reason'))=0 then raise exception 'REASON_REQUIRED';end if;
 if (p_data->>'ignore')::boolean then update public.roulette_events set status='ignored',reason=p_data->>'reason' where id=p_id;
 else if not coalesce((p_data->>'verified')::boolean,false) then raise exception 'CONFIRM_REQUIRED';end if;a=public.ensure_account(p_data->>'soop',p_data->>'nickname',(p_data->>'typeId')::uuid);perform public.append_ledger(a,(p_data->>'quantity')::numeric,'roulette',p_data->>'reason',p_id);update public.roulette_events set status='applied',reason=p_data->>'reason' where id=p_id;end if;perform public.audit('event.resolve',p_id::text);return public.operation_finish('event.resolve',p_key,jsonb_build_object('id',p_id));end$$;
create function public.update_collector_state(p_data jsonb,p_observed timestamptz) returns void language sql security definer set search_path='' as $$insert into public.collector_state(id,data,observed_at) values(true,p_data,p_observed) on conflict(id) do update set data=excluded.data,observed_at=excluded.observed_at where collector_state.observed_at<excluded.observed_at$$;
create function public.claim_live_lease() returns boolean language plpgsql security definer set search_path='' as $$begin update public.broadcast_cache set lease_until=now()+interval '15 seconds',last_attempt_at=now() where id=true and (lease_until is null or lease_until<now()) and (last_attempt_at is null or last_attempt_at<now()-interval '60 seconds');return found;end$$;
revoke all on function public.save_settings(jsonb,integer),public.save_mapping(text,uuid,numeric,boolean),public.ingest_result(uuid,text,jsonb,text,text,text),public.resolve_event(uuid,jsonb,uuid),public.update_collector_state(jsonb,timestamptz),public.claim_live_lease() from public;
grant execute on function public.save_settings(jsonb,integer),public.save_mapping(text,uuid,numeric,boolean),public.resolve_event(uuid,jsonb,uuid) to authenticated;
grant execute on function public.ingest_result(uuid,text,jsonb,text,text,text),public.update_collector_state(jsonb,timestamptz),public.claim_live_lease() to service_role;
