create function public.site_read(p_admin boolean default false) returns jsonb language plpgsql stable security definer set search_path='' as $$declare p jsonb;v integer;dates jsonb;begin if p_admin then perform public.assert_admin();end if;select data,version into p,v from public.site_profile where id=true;if not p_admin then p=jsonb_set(p,'{fields}',coalesce((select jsonb_agg(f) from jsonb_array_elements(p->'fields') f where (f->>'visible')::boolean and (not f ? 'binding' or exists(select 1 from public.anniversaries a where a.key=f->>'binding' and a.visible))),'[]'));end if;select coalesce(jsonb_agg(jsonb_build_object('id',id,'key',key,'name',name,'type',type,'date',case when type='annual' then lpad(month::text,2,'0')||'-'||lpad(day::text,2,'0') else date_value::text end,'birthYear',coalesce(birth_year::text,''),'time',coalesce(to_char(time_value,'HH24:MI'),''),'note',note,'visible',visible,'order',display_order,'version',version) order by display_order,id),'[]') into dates from public.anniversaries where p_admin or visible;return jsonb_build_object('profile',p,'anniversaries',dates,'version',v);end$$;
grant execute on function public.site_read(boolean) to anon,authenticated;

create function public.save_profile(p_data jsonb,p_dates jsonb,p_version integer,p_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare result jsonb;f jsonb;d jsonb;begin perform public.assert_admin();result=public.operation_begin('profile',p_key,jsonb_build_object('data',p_data,'dates',p_dates,'version',p_version));if result is not null then return result;end if;
 if length(p_data->>'name') not between 1 and 100 or jsonb_array_length(p_data->'fields')>40 then raise exception 'INVALID_PROFILE';end if;
 perform 1 from public.site_profile where id=true and version=p_version for update;if not found then raise exception 'VERSION_CONFLICT' using errcode='40001';end if;
 for d in select * from jsonb_array_elements(p_dates) loop
  perform 1 from public.anniversaries where key=d->>'key' and version=(d->>'version')::integer for update;if not found then raise exception 'VERSION_CONFLICT' using errcode='40001';end if;
  update public.anniversaries set date_value=case when type='annual' then null else (d->>'date')::date end,month=case when type='annual' then split_part(right(d->>'date',5),'-',1)::smallint else null end,day=case when type='annual' then split_part(right(d->>'date',5),'-',2)::smallint else null end,birth_year=case when type='annual' and length(d->>'date')=10 then left(d->>'date',4)::smallint when type='annual' then null else birth_year end,version=version+1 where key=d->>'key';
 end loop;
 update public.site_profile set data=p_data,version=version+1,updated_at=now() where id=true;perform public.audit('profile.save','site');return public.operation_finish('profile',p_key,public.site_read(true));end$$;

create function public.save_anniversary(p_id uuid,p_data jsonb,p_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare result jsonb;i uuid:=coalesce(p_id,gen_random_uuid());v integer;t text:=p_data->>'type';s text:=p_data->>'date';begin perform public.assert_admin();result=public.operation_begin('anniversary',p_key,jsonb_build_object('id',p_id,'data',p_data));if result is not null then return result;end if;if p_id is not null then select version into v from public.anniversaries where id=p_id for update;if not found or v is distinct from (p_data->>'expectedVersion')::integer then raise exception 'VERSION_CONFLICT' using errcode='40001';end if;end if;
 insert into public.anniversaries(id,key,name,type,date_value,month,day,birth_year,time_value,note,visible,display_order) values(i,p_data->>'key',p_data->>'name',t,case when t='annual' then null else s::date end,case when t='annual' then split_part(s,'-',1)::smallint end,case when t='annual' then split_part(s,'-',2)::smallint end,nullif(p_data->>'birthYear','')::smallint,nullif(p_data->>'time','')::time,p_data->>'note',(p_data->>'visible')::boolean,(p_data->>'order')::integer)
 on conflict(id) do update set name=excluded.name,type=excluded.type,date_value=excluded.date_value,month=excluded.month,day=excluded.day,birth_year=excluded.birth_year,time_value=excluded.time_value,note=excluded.note,visible=excluded.visible,display_order=excluded.display_order,version=anniversaries.version+1;
 perform public.audit('anniversary.save',i::text);return public.operation_finish('anniversary',p_key,jsonb_build_object('id',i));end$$;
create function public.delete_anniversary(p_id uuid,p_version integer,p_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare r jsonb;begin perform public.assert_admin();r=public.operation_begin('anniversary.delete',p_key,jsonb_build_object('id',p_id,'version',p_version));if r is not null then return r;end if;delete from public.anniversaries where id=p_id and version=p_version;if not found then raise exception 'VERSION_CONFLICT' using errcode='40001';end if;perform public.audit('anniversary.delete',p_id::text);return public.operation_finish('anniversary.delete',p_key,'{"deleted":true}');end$$;
create function public.save_signature(p_id uuid,p_data jsonb,p_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare r jsonb;i uuid:=coalesce(p_id,gen_random_uuid());v integer;begin perform public.assert_admin();r=public.operation_begin('signature',p_key,jsonb_build_object('id',p_id,'data',p_data));if r is not null then return r;end if;if p_id is not null then select version into v from public.signatures where id=p_id for update;if not found or v is distinct from (p_data->>'expectedVersion')::integer then raise exception 'VERSION_CONFLICT' using errcode='40001';end if;end if;
 insert into public.signatures(id,name,balloon_count,description,category,image,display_order,is_visible) values(i,p_data->>'name',(p_data->>'count')::integer,p_data->>'description',p_data->>'category',p_data->>'image',(p_data->>'order')::integer,(p_data->>'visible')::boolean) on conflict(id) do update set name=excluded.name,balloon_count=excluded.balloon_count,description=excluded.description,category=excluded.category,image=excluded.image,display_order=excluded.display_order,is_visible=excluded.is_visible,version=signatures.version+1;perform public.audit('signature.save',i::text);return public.operation_finish('signature',p_key,jsonb_build_object('id',i));end$$;

create function public.save_song(p_id uuid,p_data jsonb,p_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare r jsonb;i uuid:=coalesce(p_id,gen_random_uuid());v integer;n text;c uuid;k text;u text;begin perform public.assert_admin();r=public.operation_begin('song',p_key,jsonb_build_object('id',p_id,'data',p_data));if r is not null then return r;end if;
 if p_id is not null then select version into v from public.songs where id=p_id for update;if not found or v is distinct from (p_data->>'expectedVersion')::integer then raise exception 'VERSION_CONFLICT' using errcode='40001';end if;end if;
 if nullif(p_data->'metadata'->>'recording','') is not null then perform pg_advisory_xact_lock(hashtextextended(p_data->'metadata'->>'recording',0));if not coalesce((p_data->>'duplicateConfirmed')::boolean,false) and exists(select 1 from public.song_admin_metadata where song_id<>i and metadata->>'recording'=p_data->'metadata'->>'recording') then raise exception 'DUPLICATE_SONG' using errcode='23505';end if;end if;
 perform pg_advisory_xact_lock(hashtextextended(lower(p_data->>'title')||lower(p_data->>'artist')||coalesce(p_data->>'versionLabel',''),0));
 if not coalesce((p_data->>'duplicateConfirmed')::boolean,false) and exists(select 1 from public.songs where id<>i and lower(title)=lower(p_data->>'title') and lower(artist_name)=lower(p_data->>'artist') and version_label=p_data->>'versionLabel') then raise exception 'DUPLICATE_SONG' using errcode='23505';end if;
 insert into public.songs(id,title,artist_name,album_title,version_label,release_date_text,difficulty_steps,difficulty_note,cover_url,cover_source_url,cover_asset_id,cover_alt,is_visible,title_sort,artist_sort,search_text) values(i,p_data->>'title',p_data->>'artist',p_data->>'album',p_data->>'versionLabel',p_data->>'release',(p_data->>'steps')::smallint,p_data->>'note',p_data->>'coverUrl',p_data->>'coverSource',(p_data->>'coverAsset')::uuid,coalesce(p_data->>'coverAlt',''),(p_data->>'visible')::boolean,p_data->>'titleSort',p_data->>'artistSort',p_data->>'searchText') on conflict(id) do update set title=excluded.title,artist_name=excluded.artist_name,album_title=excluded.album_title,version_label=excluded.version_label,release_date_text=excluded.release_date_text,difficulty_steps=excluded.difficulty_steps,difficulty_note=excluded.difficulty_note,cover_url=excluded.cover_url,cover_source_url=excluded.cover_source_url,cover_asset_id=excluded.cover_asset_id,cover_alt=excluded.cover_alt,is_visible=excluded.is_visible,title_sort=excluded.title_sort,artist_sort=excluded.artist_sort,search_text=excluded.search_text,version=songs.version+1,updated_at=now();
 delete from public.song_category_links where song_id=i;
 for n in select value from jsonb_array_elements_text(p_data->'categories') loop
  insert into public.song_categories(name,normalized_name,slug) values(n,lower(normalize(trim(n),NFKC)),gen_random_uuid()::text) on conflict(normalized_name) do update set active=true returning id into c;insert into public.song_category_links(song_id,category_id) values(i,c) on conflict do nothing;
 end loop;
 foreach k in array array['original','karaoke'] loop u=p_data->>k;delete from public.song_youtube_links where song_id=i and kind=k;if u is not null then insert into public.song_youtube_links(song_id,kind,video_id,url) values(i,k,right(u,11),u);end if;end loop;
 insert into public.song_admin_metadata(song_id,memo,cover_usage_basis,metadata) values(i,p_data->>'memo',p_data->>'coverUsageBasis',p_data->'metadata') on conflict(song_id) do update set memo=excluded.memo,cover_usage_basis=excluded.cover_usage_basis,metadata=coalesce(excluded.metadata,song_admin_metadata.metadata);
 perform public.audit('song.save',i::text,jsonb_build_object('version',coalesce(v,0)+1));return public.operation_finish('song',p_key,jsonb_build_object('id',i));end$$;

create function public.manage_category(p_id uuid,p_data jsonb,p_key uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare r jsonb;i uuid:=coalesce(p_id,gen_random_uuid());begin perform public.assert_admin();r=public.operation_begin('category',p_key,jsonb_build_object('id',p_id,'data',p_data));if r is not null then return r;end if;
 if p_id is not null then perform 1 from public.song_categories where id=p_id and version=(p_data->>'expectedVersion')::integer for update;if not found then raise exception 'VERSION_CONFLICT' using errcode='40001';end if;end if;
 if p_data->>'action'='delete' then if exists(select 1 from public.song_category_links where category_id=p_id) then raise exception 'CATEGORY_IN_USE';end if;delete from public.song_categories where id=p_id;
 elsif p_data->>'action'='reassign' then if p_data->>'targetId' is not null then insert into public.song_category_links(song_id,category_id) select song_id,(p_data->>'targetId')::uuid from public.song_category_links where category_id=p_id on conflict do nothing;end if;delete from public.song_category_links where category_id=p_id;delete from public.song_categories where id=p_id;
 else insert into public.song_categories(id,name,normalized_name,slug,active,display_order) values(i,p_data->>'name',lower(normalize(trim(p_data->>'name'),NFKC)),i::text,(p_data->>'active')::boolean,coalesce((p_data->>'order')::integer,0)) on conflict(id) do update set name=excluded.name,normalized_name=excluded.normalized_name,active=excluded.active,display_order=excluded.display_order,version=song_categories.version+1;end if;
 perform public.audit('category.'||coalesce(p_data->>'action','save'),i::text);return public.operation_finish('category',p_key,jsonb_build_object('id',i));end$$;

revoke all on function public.save_profile(jsonb,jsonb,integer,uuid),public.save_anniversary(uuid,jsonb,uuid),public.delete_anniversary(uuid,integer,uuid),public.save_signature(uuid,jsonb,uuid),public.save_song(uuid,jsonb,uuid),public.manage_category(uuid,jsonb,uuid) from public;
grant execute on function public.save_profile(jsonb,jsonb,integer,uuid),public.save_anniversary(uuid,jsonb,uuid),public.delete_anniversary(uuid,integer,uuid),public.save_signature(uuid,jsonb,uuid),public.save_song(uuid,jsonb,uuid),public.manage_category(uuid,jsonb,uuid) to authenticated;
